# golangci-lint configuration file
# See https://golangci-lint.run/usage/configuration/

version: "2"
linters:
  exclusions:
    paths: []

formatters:
  enable:
    - gci
    - gofumpt
  settings:
    gci:
      sections:
        - standard
        - default
        - localmodule
