// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/dialect/sql/sqljson"
	"entgo.io/ent/schema/field"
	"github.com/safedep/vet/ent/codesignaturematch"
	"github.com/safedep/vet/ent/codesourcefile"
	"github.com/safedep/vet/ent/predicate"
)

// CodeSignatureMatchUpdate is the builder for updating CodeSignatureMatch entities.
type CodeSignatureMatchUpdate struct {
	config
	hooks    []Hook
	mutation *CodeSignatureMatchMutation
}

// Where appends a list predicates to the CodeSignatureMatchUpdate builder.
func (_u *CodeSignatureMatchUpdate) Where(ps ...predicate.CodeSignatureMatch) *CodeSignatureMatchUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetSignatureID sets the "signature_id" field.
func (_u *CodeSignatureMatchUpdate) SetSignatureID(v string) *CodeSignatureMatchUpdate {
	_u.mutation.SetSignatureID(v)
	return _u
}

// SetNillableSignatureID sets the "signature_id" field if the given value is not nil.
func (_u *CodeSignatureMatchUpdate) SetNillableSignatureID(v *string) *CodeSignatureMatchUpdate {
	if v != nil {
		_u.SetSignatureID(*v)
	}
	return _u
}

// SetSignatureVendor sets the "signature_vendor" field.
func (_u *CodeSignatureMatchUpdate) SetSignatureVendor(v string) *CodeSignatureMatchUpdate {
	_u.mutation.SetSignatureVendor(v)
	return _u
}

// SetNillableSignatureVendor sets the "signature_vendor" field if the given value is not nil.
func (_u *CodeSignatureMatchUpdate) SetNillableSignatureVendor(v *string) *CodeSignatureMatchUpdate {
	if v != nil {
		_u.SetSignatureVendor(*v)
	}
	return _u
}

// ClearSignatureVendor clears the value of the "signature_vendor" field.
func (_u *CodeSignatureMatchUpdate) ClearSignatureVendor() *CodeSignatureMatchUpdate {
	_u.mutation.ClearSignatureVendor()
	return _u
}

// SetSignatureProduct sets the "signature_product" field.
func (_u *CodeSignatureMatchUpdate) SetSignatureProduct(v string) *CodeSignatureMatchUpdate {
	_u.mutation.SetSignatureProduct(v)
	return _u
}

// SetNillableSignatureProduct sets the "signature_product" field if the given value is not nil.
func (_u *CodeSignatureMatchUpdate) SetNillableSignatureProduct(v *string) *CodeSignatureMatchUpdate {
	if v != nil {
		_u.SetSignatureProduct(*v)
	}
	return _u
}

// ClearSignatureProduct clears the value of the "signature_product" field.
func (_u *CodeSignatureMatchUpdate) ClearSignatureProduct() *CodeSignatureMatchUpdate {
	_u.mutation.ClearSignatureProduct()
	return _u
}

// SetSignatureService sets the "signature_service" field.
func (_u *CodeSignatureMatchUpdate) SetSignatureService(v string) *CodeSignatureMatchUpdate {
	_u.mutation.SetSignatureService(v)
	return _u
}

// SetNillableSignatureService sets the "signature_service" field if the given value is not nil.
func (_u *CodeSignatureMatchUpdate) SetNillableSignatureService(v *string) *CodeSignatureMatchUpdate {
	if v != nil {
		_u.SetSignatureService(*v)
	}
	return _u
}

// ClearSignatureService clears the value of the "signature_service" field.
func (_u *CodeSignatureMatchUpdate) ClearSignatureService() *CodeSignatureMatchUpdate {
	_u.mutation.ClearSignatureService()
	return _u
}

// SetSignatureDescription sets the "signature_description" field.
func (_u *CodeSignatureMatchUpdate) SetSignatureDescription(v string) *CodeSignatureMatchUpdate {
	_u.mutation.SetSignatureDescription(v)
	return _u
}

// SetNillableSignatureDescription sets the "signature_description" field if the given value is not nil.
func (_u *CodeSignatureMatchUpdate) SetNillableSignatureDescription(v *string) *CodeSignatureMatchUpdate {
	if v != nil {
		_u.SetSignatureDescription(*v)
	}
	return _u
}

// ClearSignatureDescription clears the value of the "signature_description" field.
func (_u *CodeSignatureMatchUpdate) ClearSignatureDescription() *CodeSignatureMatchUpdate {
	_u.mutation.ClearSignatureDescription()
	return _u
}

// SetTags sets the "tags" field.
func (_u *CodeSignatureMatchUpdate) SetTags(v []string) *CodeSignatureMatchUpdate {
	_u.mutation.SetTags(v)
	return _u
}

// AppendTags appends value to the "tags" field.
func (_u *CodeSignatureMatchUpdate) AppendTags(v []string) *CodeSignatureMatchUpdate {
	_u.mutation.AppendTags(v)
	return _u
}

// ClearTags clears the value of the "tags" field.
func (_u *CodeSignatureMatchUpdate) ClearTags() *CodeSignatureMatchUpdate {
	_u.mutation.ClearTags()
	return _u
}

// SetFilePath sets the "file_path" field.
func (_u *CodeSignatureMatchUpdate) SetFilePath(v string) *CodeSignatureMatchUpdate {
	_u.mutation.SetFilePath(v)
	return _u
}

// SetNillableFilePath sets the "file_path" field if the given value is not nil.
func (_u *CodeSignatureMatchUpdate) SetNillableFilePath(v *string) *CodeSignatureMatchUpdate {
	if v != nil {
		_u.SetFilePath(*v)
	}
	return _u
}

// SetLanguage sets the "language" field.
func (_u *CodeSignatureMatchUpdate) SetLanguage(v string) *CodeSignatureMatchUpdate {
	_u.mutation.SetLanguage(v)
	return _u
}

// SetNillableLanguage sets the "language" field if the given value is not nil.
func (_u *CodeSignatureMatchUpdate) SetNillableLanguage(v *string) *CodeSignatureMatchUpdate {
	if v != nil {
		_u.SetLanguage(*v)
	}
	return _u
}

// SetLine sets the "line" field.
func (_u *CodeSignatureMatchUpdate) SetLine(v uint) *CodeSignatureMatchUpdate {
	_u.mutation.ResetLine()
	_u.mutation.SetLine(v)
	return _u
}

// SetNillableLine sets the "line" field if the given value is not nil.
func (_u *CodeSignatureMatchUpdate) SetNillableLine(v *uint) *CodeSignatureMatchUpdate {
	if v != nil {
		_u.SetLine(*v)
	}
	return _u
}

// AddLine adds value to the "line" field.
func (_u *CodeSignatureMatchUpdate) AddLine(v int) *CodeSignatureMatchUpdate {
	_u.mutation.AddLine(v)
	return _u
}

// ClearLine clears the value of the "line" field.
func (_u *CodeSignatureMatchUpdate) ClearLine() *CodeSignatureMatchUpdate {
	_u.mutation.ClearLine()
	return _u
}

// SetColumn sets the "column" field.
func (_u *CodeSignatureMatchUpdate) SetColumn(v uint) *CodeSignatureMatchUpdate {
	_u.mutation.ResetColumn()
	_u.mutation.SetColumn(v)
	return _u
}

// SetNillableColumn sets the "column" field if the given value is not nil.
func (_u *CodeSignatureMatchUpdate) SetNillableColumn(v *uint) *CodeSignatureMatchUpdate {
	if v != nil {
		_u.SetColumn(*v)
	}
	return _u
}

// AddColumn adds value to the "column" field.
func (_u *CodeSignatureMatchUpdate) AddColumn(v int) *CodeSignatureMatchUpdate {
	_u.mutation.AddColumn(v)
	return _u
}

// ClearColumn clears the value of the "column" field.
func (_u *CodeSignatureMatchUpdate) ClearColumn() *CodeSignatureMatchUpdate {
	_u.mutation.ClearColumn()
	return _u
}

// SetCalleeNamespace sets the "callee_namespace" field.
func (_u *CodeSignatureMatchUpdate) SetCalleeNamespace(v string) *CodeSignatureMatchUpdate {
	_u.mutation.SetCalleeNamespace(v)
	return _u
}

// SetNillableCalleeNamespace sets the "callee_namespace" field if the given value is not nil.
func (_u *CodeSignatureMatchUpdate) SetNillableCalleeNamespace(v *string) *CodeSignatureMatchUpdate {
	if v != nil {
		_u.SetCalleeNamespace(*v)
	}
	return _u
}

// ClearCalleeNamespace clears the value of the "callee_namespace" field.
func (_u *CodeSignatureMatchUpdate) ClearCalleeNamespace() *CodeSignatureMatchUpdate {
	_u.mutation.ClearCalleeNamespace()
	return _u
}

// SetMatchedCall sets the "matched_call" field.
func (_u *CodeSignatureMatchUpdate) SetMatchedCall(v string) *CodeSignatureMatchUpdate {
	_u.mutation.SetMatchedCall(v)
	return _u
}

// SetNillableMatchedCall sets the "matched_call" field if the given value is not nil.
func (_u *CodeSignatureMatchUpdate) SetNillableMatchedCall(v *string) *CodeSignatureMatchUpdate {
	if v != nil {
		_u.SetMatchedCall(*v)
	}
	return _u
}

// ClearMatchedCall clears the value of the "matched_call" field.
func (_u *CodeSignatureMatchUpdate) ClearMatchedCall() *CodeSignatureMatchUpdate {
	_u.mutation.ClearMatchedCall()
	return _u
}

// SetPackageHint sets the "package_hint" field.
func (_u *CodeSignatureMatchUpdate) SetPackageHint(v string) *CodeSignatureMatchUpdate {
	_u.mutation.SetPackageHint(v)
	return _u
}

// SetNillablePackageHint sets the "package_hint" field if the given value is not nil.
func (_u *CodeSignatureMatchUpdate) SetNillablePackageHint(v *string) *CodeSignatureMatchUpdate {
	if v != nil {
		_u.SetPackageHint(*v)
	}
	return _u
}

// ClearPackageHint clears the value of the "package_hint" field.
func (_u *CodeSignatureMatchUpdate) ClearPackageHint() *CodeSignatureMatchUpdate {
	_u.mutation.ClearPackageHint()
	return _u
}

// SetSourceFileID sets the "source_file" edge to the CodeSourceFile entity by ID.
func (_u *CodeSignatureMatchUpdate) SetSourceFileID(id int) *CodeSignatureMatchUpdate {
	_u.mutation.SetSourceFileID(id)
	return _u
}

// SetSourceFile sets the "source_file" edge to the CodeSourceFile entity.
func (_u *CodeSignatureMatchUpdate) SetSourceFile(v *CodeSourceFile) *CodeSignatureMatchUpdate {
	return _u.SetSourceFileID(v.ID)
}

// Mutation returns the CodeSignatureMatchMutation object of the builder.
func (_u *CodeSignatureMatchUpdate) Mutation() *CodeSignatureMatchMutation {
	return _u.mutation
}

// ClearSourceFile clears the "source_file" edge to the CodeSourceFile entity.
func (_u *CodeSignatureMatchUpdate) ClearSourceFile() *CodeSignatureMatchUpdate {
	_u.mutation.ClearSourceFile()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *CodeSignatureMatchUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *CodeSignatureMatchUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *CodeSignatureMatchUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *CodeSignatureMatchUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *CodeSignatureMatchUpdate) check() error {
	if v, ok := _u.mutation.SignatureID(); ok {
		if err := codesignaturematch.SignatureIDValidator(v); err != nil {
			return &ValidationError{Name: "signature_id", err: fmt.Errorf(`ent: validator failed for field "CodeSignatureMatch.signature_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.FilePath(); ok {
		if err := codesignaturematch.FilePathValidator(v); err != nil {
			return &ValidationError{Name: "file_path", err: fmt.Errorf(`ent: validator failed for field "CodeSignatureMatch.file_path": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Language(); ok {
		if err := codesignaturematch.LanguageValidator(v); err != nil {
			return &ValidationError{Name: "language", err: fmt.Errorf(`ent: validator failed for field "CodeSignatureMatch.language": %w`, err)}
		}
	}
	if _u.mutation.SourceFileCleared() && len(_u.mutation.SourceFileIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "CodeSignatureMatch.source_file"`)
	}
	return nil
}

func (_u *CodeSignatureMatchUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(codesignaturematch.Table, codesignaturematch.Columns, sqlgraph.NewFieldSpec(codesignaturematch.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.SignatureID(); ok {
		_spec.SetField(codesignaturematch.FieldSignatureID, field.TypeString, value)
	}
	if value, ok := _u.mutation.SignatureVendor(); ok {
		_spec.SetField(codesignaturematch.FieldSignatureVendor, field.TypeString, value)
	}
	if _u.mutation.SignatureVendorCleared() {
		_spec.ClearField(codesignaturematch.FieldSignatureVendor, field.TypeString)
	}
	if value, ok := _u.mutation.SignatureProduct(); ok {
		_spec.SetField(codesignaturematch.FieldSignatureProduct, field.TypeString, value)
	}
	if _u.mutation.SignatureProductCleared() {
		_spec.ClearField(codesignaturematch.FieldSignatureProduct, field.TypeString)
	}
	if value, ok := _u.mutation.SignatureService(); ok {
		_spec.SetField(codesignaturematch.FieldSignatureService, field.TypeString, value)
	}
	if _u.mutation.SignatureServiceCleared() {
		_spec.ClearField(codesignaturematch.FieldSignatureService, field.TypeString)
	}
	if value, ok := _u.mutation.SignatureDescription(); ok {
		_spec.SetField(codesignaturematch.FieldSignatureDescription, field.TypeString, value)
	}
	if _u.mutation.SignatureDescriptionCleared() {
		_spec.ClearField(codesignaturematch.FieldSignatureDescription, field.TypeString)
	}
	if value, ok := _u.mutation.Tags(); ok {
		_spec.SetField(codesignaturematch.FieldTags, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedTags(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, codesignaturematch.FieldTags, value)
		})
	}
	if _u.mutation.TagsCleared() {
		_spec.ClearField(codesignaturematch.FieldTags, field.TypeJSON)
	}
	if value, ok := _u.mutation.FilePath(); ok {
		_spec.SetField(codesignaturematch.FieldFilePath, field.TypeString, value)
	}
	if value, ok := _u.mutation.Language(); ok {
		_spec.SetField(codesignaturematch.FieldLanguage, field.TypeString, value)
	}
	if value, ok := _u.mutation.Line(); ok {
		_spec.SetField(codesignaturematch.FieldLine, field.TypeUint, value)
	}
	if value, ok := _u.mutation.AddedLine(); ok {
		_spec.AddField(codesignaturematch.FieldLine, field.TypeUint, value)
	}
	if _u.mutation.LineCleared() {
		_spec.ClearField(codesignaturematch.FieldLine, field.TypeUint)
	}
	if value, ok := _u.mutation.Column(); ok {
		_spec.SetField(codesignaturematch.FieldColumn, field.TypeUint, value)
	}
	if value, ok := _u.mutation.AddedColumn(); ok {
		_spec.AddField(codesignaturematch.FieldColumn, field.TypeUint, value)
	}
	if _u.mutation.ColumnCleared() {
		_spec.ClearField(codesignaturematch.FieldColumn, field.TypeUint)
	}
	if value, ok := _u.mutation.CalleeNamespace(); ok {
		_spec.SetField(codesignaturematch.FieldCalleeNamespace, field.TypeString, value)
	}
	if _u.mutation.CalleeNamespaceCleared() {
		_spec.ClearField(codesignaturematch.FieldCalleeNamespace, field.TypeString)
	}
	if value, ok := _u.mutation.MatchedCall(); ok {
		_spec.SetField(codesignaturematch.FieldMatchedCall, field.TypeString, value)
	}
	if _u.mutation.MatchedCallCleared() {
		_spec.ClearField(codesignaturematch.FieldMatchedCall, field.TypeString)
	}
	if value, ok := _u.mutation.PackageHint(); ok {
		_spec.SetField(codesignaturematch.FieldPackageHint, field.TypeString, value)
	}
	if _u.mutation.PackageHintCleared() {
		_spec.ClearField(codesignaturematch.FieldPackageHint, field.TypeString)
	}
	if _u.mutation.SourceFileCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   codesignaturematch.SourceFileTable,
			Columns: []string{codesignaturematch.SourceFileColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(codesourcefile.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.SourceFileIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   codesignaturematch.SourceFileTable,
			Columns: []string{codesignaturematch.SourceFileColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(codesourcefile.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{codesignaturematch.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// CodeSignatureMatchUpdateOne is the builder for updating a single CodeSignatureMatch entity.
type CodeSignatureMatchUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *CodeSignatureMatchMutation
}

// SetSignatureID sets the "signature_id" field.
func (_u *CodeSignatureMatchUpdateOne) SetSignatureID(v string) *CodeSignatureMatchUpdateOne {
	_u.mutation.SetSignatureID(v)
	return _u
}

// SetNillableSignatureID sets the "signature_id" field if the given value is not nil.
func (_u *CodeSignatureMatchUpdateOne) SetNillableSignatureID(v *string) *CodeSignatureMatchUpdateOne {
	if v != nil {
		_u.SetSignatureID(*v)
	}
	return _u
}

// SetSignatureVendor sets the "signature_vendor" field.
func (_u *CodeSignatureMatchUpdateOne) SetSignatureVendor(v string) *CodeSignatureMatchUpdateOne {
	_u.mutation.SetSignatureVendor(v)
	return _u
}

// SetNillableSignatureVendor sets the "signature_vendor" field if the given value is not nil.
func (_u *CodeSignatureMatchUpdateOne) SetNillableSignatureVendor(v *string) *CodeSignatureMatchUpdateOne {
	if v != nil {
		_u.SetSignatureVendor(*v)
	}
	return _u
}

// ClearSignatureVendor clears the value of the "signature_vendor" field.
func (_u *CodeSignatureMatchUpdateOne) ClearSignatureVendor() *CodeSignatureMatchUpdateOne {
	_u.mutation.ClearSignatureVendor()
	return _u
}

// SetSignatureProduct sets the "signature_product" field.
func (_u *CodeSignatureMatchUpdateOne) SetSignatureProduct(v string) *CodeSignatureMatchUpdateOne {
	_u.mutation.SetSignatureProduct(v)
	return _u
}

// SetNillableSignatureProduct sets the "signature_product" field if the given value is not nil.
func (_u *CodeSignatureMatchUpdateOne) SetNillableSignatureProduct(v *string) *CodeSignatureMatchUpdateOne {
	if v != nil {
		_u.SetSignatureProduct(*v)
	}
	return _u
}

// ClearSignatureProduct clears the value of the "signature_product" field.
func (_u *CodeSignatureMatchUpdateOne) ClearSignatureProduct() *CodeSignatureMatchUpdateOne {
	_u.mutation.ClearSignatureProduct()
	return _u
}

// SetSignatureService sets the "signature_service" field.
func (_u *CodeSignatureMatchUpdateOne) SetSignatureService(v string) *CodeSignatureMatchUpdateOne {
	_u.mutation.SetSignatureService(v)
	return _u
}

// SetNillableSignatureService sets the "signature_service" field if the given value is not nil.
func (_u *CodeSignatureMatchUpdateOne) SetNillableSignatureService(v *string) *CodeSignatureMatchUpdateOne {
	if v != nil {
		_u.SetSignatureService(*v)
	}
	return _u
}

// ClearSignatureService clears the value of the "signature_service" field.
func (_u *CodeSignatureMatchUpdateOne) ClearSignatureService() *CodeSignatureMatchUpdateOne {
	_u.mutation.ClearSignatureService()
	return _u
}

// SetSignatureDescription sets the "signature_description" field.
func (_u *CodeSignatureMatchUpdateOne) SetSignatureDescription(v string) *CodeSignatureMatchUpdateOne {
	_u.mutation.SetSignatureDescription(v)
	return _u
}

// SetNillableSignatureDescription sets the "signature_description" field if the given value is not nil.
func (_u *CodeSignatureMatchUpdateOne) SetNillableSignatureDescription(v *string) *CodeSignatureMatchUpdateOne {
	if v != nil {
		_u.SetSignatureDescription(*v)
	}
	return _u
}

// ClearSignatureDescription clears the value of the "signature_description" field.
func (_u *CodeSignatureMatchUpdateOne) ClearSignatureDescription() *CodeSignatureMatchUpdateOne {
	_u.mutation.ClearSignatureDescription()
	return _u
}

// SetTags sets the "tags" field.
func (_u *CodeSignatureMatchUpdateOne) SetTags(v []string) *CodeSignatureMatchUpdateOne {
	_u.mutation.SetTags(v)
	return _u
}

// AppendTags appends value to the "tags" field.
func (_u *CodeSignatureMatchUpdateOne) AppendTags(v []string) *CodeSignatureMatchUpdateOne {
	_u.mutation.AppendTags(v)
	return _u
}

// ClearTags clears the value of the "tags" field.
func (_u *CodeSignatureMatchUpdateOne) ClearTags() *CodeSignatureMatchUpdateOne {
	_u.mutation.ClearTags()
	return _u
}

// SetFilePath sets the "file_path" field.
func (_u *CodeSignatureMatchUpdateOne) SetFilePath(v string) *CodeSignatureMatchUpdateOne {
	_u.mutation.SetFilePath(v)
	return _u
}

// SetNillableFilePath sets the "file_path" field if the given value is not nil.
func (_u *CodeSignatureMatchUpdateOne) SetNillableFilePath(v *string) *CodeSignatureMatchUpdateOne {
	if v != nil {
		_u.SetFilePath(*v)
	}
	return _u
}

// SetLanguage sets the "language" field.
func (_u *CodeSignatureMatchUpdateOne) SetLanguage(v string) *CodeSignatureMatchUpdateOne {
	_u.mutation.SetLanguage(v)
	return _u
}

// SetNillableLanguage sets the "language" field if the given value is not nil.
func (_u *CodeSignatureMatchUpdateOne) SetNillableLanguage(v *string) *CodeSignatureMatchUpdateOne {
	if v != nil {
		_u.SetLanguage(*v)
	}
	return _u
}

// SetLine sets the "line" field.
func (_u *CodeSignatureMatchUpdateOne) SetLine(v uint) *CodeSignatureMatchUpdateOne {
	_u.mutation.ResetLine()
	_u.mutation.SetLine(v)
	return _u
}

// SetNillableLine sets the "line" field if the given value is not nil.
func (_u *CodeSignatureMatchUpdateOne) SetNillableLine(v *uint) *CodeSignatureMatchUpdateOne {
	if v != nil {
		_u.SetLine(*v)
	}
	return _u
}

// AddLine adds value to the "line" field.
func (_u *CodeSignatureMatchUpdateOne) AddLine(v int) *CodeSignatureMatchUpdateOne {
	_u.mutation.AddLine(v)
	return _u
}

// ClearLine clears the value of the "line" field.
func (_u *CodeSignatureMatchUpdateOne) ClearLine() *CodeSignatureMatchUpdateOne {
	_u.mutation.ClearLine()
	return _u
}

// SetColumn sets the "column" field.
func (_u *CodeSignatureMatchUpdateOne) SetColumn(v uint) *CodeSignatureMatchUpdateOne {
	_u.mutation.ResetColumn()
	_u.mutation.SetColumn(v)
	return _u
}

// SetNillableColumn sets the "column" field if the given value is not nil.
func (_u *CodeSignatureMatchUpdateOne) SetNillableColumn(v *uint) *CodeSignatureMatchUpdateOne {
	if v != nil {
		_u.SetColumn(*v)
	}
	return _u
}

// AddColumn adds value to the "column" field.
func (_u *CodeSignatureMatchUpdateOne) AddColumn(v int) *CodeSignatureMatchUpdateOne {
	_u.mutation.AddColumn(v)
	return _u
}

// ClearColumn clears the value of the "column" field.
func (_u *CodeSignatureMatchUpdateOne) ClearColumn() *CodeSignatureMatchUpdateOne {
	_u.mutation.ClearColumn()
	return _u
}

// SetCalleeNamespace sets the "callee_namespace" field.
func (_u *CodeSignatureMatchUpdateOne) SetCalleeNamespace(v string) *CodeSignatureMatchUpdateOne {
	_u.mutation.SetCalleeNamespace(v)
	return _u
}

// SetNillableCalleeNamespace sets the "callee_namespace" field if the given value is not nil.
func (_u *CodeSignatureMatchUpdateOne) SetNillableCalleeNamespace(v *string) *CodeSignatureMatchUpdateOne {
	if v != nil {
		_u.SetCalleeNamespace(*v)
	}
	return _u
}

// ClearCalleeNamespace clears the value of the "callee_namespace" field.
func (_u *CodeSignatureMatchUpdateOne) ClearCalleeNamespace() *CodeSignatureMatchUpdateOne {
	_u.mutation.ClearCalleeNamespace()
	return _u
}

// SetMatchedCall sets the "matched_call" field.
func (_u *CodeSignatureMatchUpdateOne) SetMatchedCall(v string) *CodeSignatureMatchUpdateOne {
	_u.mutation.SetMatchedCall(v)
	return _u
}

// SetNillableMatchedCall sets the "matched_call" field if the given value is not nil.
func (_u *CodeSignatureMatchUpdateOne) SetNillableMatchedCall(v *string) *CodeSignatureMatchUpdateOne {
	if v != nil {
		_u.SetMatchedCall(*v)
	}
	return _u
}

// ClearMatchedCall clears the value of the "matched_call" field.
func (_u *CodeSignatureMatchUpdateOne) ClearMatchedCall() *CodeSignatureMatchUpdateOne {
	_u.mutation.ClearMatchedCall()
	return _u
}

// SetPackageHint sets the "package_hint" field.
func (_u *CodeSignatureMatchUpdateOne) SetPackageHint(v string) *CodeSignatureMatchUpdateOne {
	_u.mutation.SetPackageHint(v)
	return _u
}

// SetNillablePackageHint sets the "package_hint" field if the given value is not nil.
func (_u *CodeSignatureMatchUpdateOne) SetNillablePackageHint(v *string) *CodeSignatureMatchUpdateOne {
	if v != nil {
		_u.SetPackageHint(*v)
	}
	return _u
}

// ClearPackageHint clears the value of the "package_hint" field.
func (_u *CodeSignatureMatchUpdateOne) ClearPackageHint() *CodeSignatureMatchUpdateOne {
	_u.mutation.ClearPackageHint()
	return _u
}

// SetSourceFileID sets the "source_file" edge to the CodeSourceFile entity by ID.
func (_u *CodeSignatureMatchUpdateOne) SetSourceFileID(id int) *CodeSignatureMatchUpdateOne {
	_u.mutation.SetSourceFileID(id)
	return _u
}

// SetSourceFile sets the "source_file" edge to the CodeSourceFile entity.
func (_u *CodeSignatureMatchUpdateOne) SetSourceFile(v *CodeSourceFile) *CodeSignatureMatchUpdateOne {
	return _u.SetSourceFileID(v.ID)
}

// Mutation returns the CodeSignatureMatchMutation object of the builder.
func (_u *CodeSignatureMatchUpdateOne) Mutation() *CodeSignatureMatchMutation {
	return _u.mutation
}

// ClearSourceFile clears the "source_file" edge to the CodeSourceFile entity.
func (_u *CodeSignatureMatchUpdateOne) ClearSourceFile() *CodeSignatureMatchUpdateOne {
	_u.mutation.ClearSourceFile()
	return _u
}

// Where appends a list predicates to the CodeSignatureMatchUpdate builder.
func (_u *CodeSignatureMatchUpdateOne) Where(ps ...predicate.CodeSignatureMatch) *CodeSignatureMatchUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *CodeSignatureMatchUpdateOne) Select(field string, fields ...string) *CodeSignatureMatchUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated CodeSignatureMatch entity.
func (_u *CodeSignatureMatchUpdateOne) Save(ctx context.Context) (*CodeSignatureMatch, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *CodeSignatureMatchUpdateOne) SaveX(ctx context.Context) *CodeSignatureMatch {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *CodeSignatureMatchUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *CodeSignatureMatchUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *CodeSignatureMatchUpdateOne) check() error {
	if v, ok := _u.mutation.SignatureID(); ok {
		if err := codesignaturematch.SignatureIDValidator(v); err != nil {
			return &ValidationError{Name: "signature_id", err: fmt.Errorf(`ent: validator failed for field "CodeSignatureMatch.signature_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.FilePath(); ok {
		if err := codesignaturematch.FilePathValidator(v); err != nil {
			return &ValidationError{Name: "file_path", err: fmt.Errorf(`ent: validator failed for field "CodeSignatureMatch.file_path": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Language(); ok {
		if err := codesignaturematch.LanguageValidator(v); err != nil {
			return &ValidationError{Name: "language", err: fmt.Errorf(`ent: validator failed for field "CodeSignatureMatch.language": %w`, err)}
		}
	}
	if _u.mutation.SourceFileCleared() && len(_u.mutation.SourceFileIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "CodeSignatureMatch.source_file"`)
	}
	return nil
}

func (_u *CodeSignatureMatchUpdateOne) sqlSave(ctx context.Context) (_node *CodeSignatureMatch, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(codesignaturematch.Table, codesignaturematch.Columns, sqlgraph.NewFieldSpec(codesignaturematch.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "CodeSignatureMatch.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, codesignaturematch.FieldID)
		for _, f := range fields {
			if !codesignaturematch.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != codesignaturematch.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.SignatureID(); ok {
		_spec.SetField(codesignaturematch.FieldSignatureID, field.TypeString, value)
	}
	if value, ok := _u.mutation.SignatureVendor(); ok {
		_spec.SetField(codesignaturematch.FieldSignatureVendor, field.TypeString, value)
	}
	if _u.mutation.SignatureVendorCleared() {
		_spec.ClearField(codesignaturematch.FieldSignatureVendor, field.TypeString)
	}
	if value, ok := _u.mutation.SignatureProduct(); ok {
		_spec.SetField(codesignaturematch.FieldSignatureProduct, field.TypeString, value)
	}
	if _u.mutation.SignatureProductCleared() {
		_spec.ClearField(codesignaturematch.FieldSignatureProduct, field.TypeString)
	}
	if value, ok := _u.mutation.SignatureService(); ok {
		_spec.SetField(codesignaturematch.FieldSignatureService, field.TypeString, value)
	}
	if _u.mutation.SignatureServiceCleared() {
		_spec.ClearField(codesignaturematch.FieldSignatureService, field.TypeString)
	}
	if value, ok := _u.mutation.SignatureDescription(); ok {
		_spec.SetField(codesignaturematch.FieldSignatureDescription, field.TypeString, value)
	}
	if _u.mutation.SignatureDescriptionCleared() {
		_spec.ClearField(codesignaturematch.FieldSignatureDescription, field.TypeString)
	}
	if value, ok := _u.mutation.Tags(); ok {
		_spec.SetField(codesignaturematch.FieldTags, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedTags(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, codesignaturematch.FieldTags, value)
		})
	}
	if _u.mutation.TagsCleared() {
		_spec.ClearField(codesignaturematch.FieldTags, field.TypeJSON)
	}
	if value, ok := _u.mutation.FilePath(); ok {
		_spec.SetField(codesignaturematch.FieldFilePath, field.TypeString, value)
	}
	if value, ok := _u.mutation.Language(); ok {
		_spec.SetField(codesignaturematch.FieldLanguage, field.TypeString, value)
	}
	if value, ok := _u.mutation.Line(); ok {
		_spec.SetField(codesignaturematch.FieldLine, field.TypeUint, value)
	}
	if value, ok := _u.mutation.AddedLine(); ok {
		_spec.AddField(codesignaturematch.FieldLine, field.TypeUint, value)
	}
	if _u.mutation.LineCleared() {
		_spec.ClearField(codesignaturematch.FieldLine, field.TypeUint)
	}
	if value, ok := _u.mutation.Column(); ok {
		_spec.SetField(codesignaturematch.FieldColumn, field.TypeUint, value)
	}
	if value, ok := _u.mutation.AddedColumn(); ok {
		_spec.AddField(codesignaturematch.FieldColumn, field.TypeUint, value)
	}
	if _u.mutation.ColumnCleared() {
		_spec.ClearField(codesignaturematch.FieldColumn, field.TypeUint)
	}
	if value, ok := _u.mutation.CalleeNamespace(); ok {
		_spec.SetField(codesignaturematch.FieldCalleeNamespace, field.TypeString, value)
	}
	if _u.mutation.CalleeNamespaceCleared() {
		_spec.ClearField(codesignaturematch.FieldCalleeNamespace, field.TypeString)
	}
	if value, ok := _u.mutation.MatchedCall(); ok {
		_spec.SetField(codesignaturematch.FieldMatchedCall, field.TypeString, value)
	}
	if _u.mutation.MatchedCallCleared() {
		_spec.ClearField(codesignaturematch.FieldMatchedCall, field.TypeString)
	}
	if value, ok := _u.mutation.PackageHint(); ok {
		_spec.SetField(codesignaturematch.FieldPackageHint, field.TypeString, value)
	}
	if _u.mutation.PackageHintCleared() {
		_spec.ClearField(codesignaturematch.FieldPackageHint, field.TypeString)
	}
	if _u.mutation.SourceFileCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   codesignaturematch.SourceFileTable,
			Columns: []string{codesignaturematch.SourceFileColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(codesourcefile.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.SourceFileIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   codesignaturematch.SourceFileTable,
			Columns: []string{codesignaturematch.SourceFileColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(codesourcefile.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &CodeSignatureMatch{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{codesignaturematch.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
