// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"database/sql/driver"
	"fmt"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/safedep/vet/ent/codesignaturematch"
	"github.com/safedep/vet/ent/codesourcefile"
	"github.com/safedep/vet/ent/depsusageevidence"
	"github.com/safedep/vet/ent/predicate"
)

// CodeSourceFileQuery is the builder for querying CodeSourceFile entities.
type CodeSourceFileQuery struct {
	config
	ctx                    *QueryContext
	order                  []codesourcefile.OrderOption
	inters                 []Interceptor
	predicates             []predicate.CodeSourceFile
	withDepsUsageEvidences *DepsUsageEvidenceQuery
	withSignatureMatches   *CodeSignatureMatchQuery
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the CodeSourceFileQuery builder.
func (_q *CodeSourceFileQuery) Where(ps ...predicate.CodeSourceFile) *CodeSourceFileQuery {
	_q.predicates = append(_q.predicates, ps...)
	return _q
}

// Limit the number of records to be returned by this query.
func (_q *CodeSourceFileQuery) Limit(limit int) *CodeSourceFileQuery {
	_q.ctx.Limit = &limit
	return _q
}

// Offset to start from.
func (_q *CodeSourceFileQuery) Offset(offset int) *CodeSourceFileQuery {
	_q.ctx.Offset = &offset
	return _q
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (_q *CodeSourceFileQuery) Unique(unique bool) *CodeSourceFileQuery {
	_q.ctx.Unique = &unique
	return _q
}

// Order specifies how the records should be ordered.
func (_q *CodeSourceFileQuery) Order(o ...codesourcefile.OrderOption) *CodeSourceFileQuery {
	_q.order = append(_q.order, o...)
	return _q
}

// QueryDepsUsageEvidences chains the current query on the "deps_usage_evidences" edge.
func (_q *CodeSourceFileQuery) QueryDepsUsageEvidences() *DepsUsageEvidenceQuery {
	query := (&DepsUsageEvidenceClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(codesourcefile.Table, codesourcefile.FieldID, selector),
			sqlgraph.To(depsusageevidence.Table, depsusageevidence.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, true, codesourcefile.DepsUsageEvidencesTable, codesourcefile.DepsUsageEvidencesColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QuerySignatureMatches chains the current query on the "signature_matches" edge.
func (_q *CodeSourceFileQuery) QuerySignatureMatches() *CodeSignatureMatchQuery {
	query := (&CodeSignatureMatchClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(codesourcefile.Table, codesourcefile.FieldID, selector),
			sqlgraph.To(codesignaturematch.Table, codesignaturematch.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, true, codesourcefile.SignatureMatchesTable, codesourcefile.SignatureMatchesColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first CodeSourceFile entity from the query.
// Returns a *NotFoundError when no CodeSourceFile was found.
func (_q *CodeSourceFileQuery) First(ctx context.Context) (*CodeSourceFile, error) {
	nodes, err := _q.Limit(1).All(setContextOp(ctx, _q.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{codesourcefile.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (_q *CodeSourceFileQuery) FirstX(ctx context.Context) *CodeSourceFile {
	node, err := _q.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first CodeSourceFile ID from the query.
// Returns a *NotFoundError when no CodeSourceFile ID was found.
func (_q *CodeSourceFileQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = _q.Limit(1).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{codesourcefile.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (_q *CodeSourceFileQuery) FirstIDX(ctx context.Context) int {
	id, err := _q.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single CodeSourceFile entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one CodeSourceFile entity is found.
// Returns a *NotFoundError when no CodeSourceFile entities are found.
func (_q *CodeSourceFileQuery) Only(ctx context.Context) (*CodeSourceFile, error) {
	nodes, err := _q.Limit(2).All(setContextOp(ctx, _q.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{codesourcefile.Label}
	default:
		return nil, &NotSingularError{codesourcefile.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (_q *CodeSourceFileQuery) OnlyX(ctx context.Context) *CodeSourceFile {
	node, err := _q.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only CodeSourceFile ID in the query.
// Returns a *NotSingularError when more than one CodeSourceFile ID is found.
// Returns a *NotFoundError when no entities are found.
func (_q *CodeSourceFileQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = _q.Limit(2).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{codesourcefile.Label}
	default:
		err = &NotSingularError{codesourcefile.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (_q *CodeSourceFileQuery) OnlyIDX(ctx context.Context) int {
	id, err := _q.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of CodeSourceFiles.
func (_q *CodeSourceFileQuery) All(ctx context.Context) ([]*CodeSourceFile, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryAll)
	if err := _q.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*CodeSourceFile, *CodeSourceFileQuery]()
	return withInterceptors[[]*CodeSourceFile](ctx, _q, qr, _q.inters)
}

// AllX is like All, but panics if an error occurs.
func (_q *CodeSourceFileQuery) AllX(ctx context.Context) []*CodeSourceFile {
	nodes, err := _q.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of CodeSourceFile IDs.
func (_q *CodeSourceFileQuery) IDs(ctx context.Context) (ids []int, err error) {
	if _q.ctx.Unique == nil && _q.path != nil {
		_q.Unique(true)
	}
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryIDs)
	if err = _q.Select(codesourcefile.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (_q *CodeSourceFileQuery) IDsX(ctx context.Context) []int {
	ids, err := _q.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (_q *CodeSourceFileQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryCount)
	if err := _q.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, _q, querierCount[*CodeSourceFileQuery](), _q.inters)
}

// CountX is like Count, but panics if an error occurs.
func (_q *CodeSourceFileQuery) CountX(ctx context.Context) int {
	count, err := _q.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (_q *CodeSourceFileQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryExist)
	switch _, err := _q.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (_q *CodeSourceFileQuery) ExistX(ctx context.Context) bool {
	exist, err := _q.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the CodeSourceFileQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (_q *CodeSourceFileQuery) Clone() *CodeSourceFileQuery {
	if _q == nil {
		return nil
	}
	return &CodeSourceFileQuery{
		config:                 _q.config,
		ctx:                    _q.ctx.Clone(),
		order:                  append([]codesourcefile.OrderOption{}, _q.order...),
		inters:                 append([]Interceptor{}, _q.inters...),
		predicates:             append([]predicate.CodeSourceFile{}, _q.predicates...),
		withDepsUsageEvidences: _q.withDepsUsageEvidences.Clone(),
		withSignatureMatches:   _q.withSignatureMatches.Clone(),
		// clone intermediate query.
		sql:  _q.sql.Clone(),
		path: _q.path,
	}
}

// WithDepsUsageEvidences tells the query-builder to eager-load the nodes that are connected to
// the "deps_usage_evidences" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *CodeSourceFileQuery) WithDepsUsageEvidences(opts ...func(*DepsUsageEvidenceQuery)) *CodeSourceFileQuery {
	query := (&DepsUsageEvidenceClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withDepsUsageEvidences = query
	return _q
}

// WithSignatureMatches tells the query-builder to eager-load the nodes that are connected to
// the "signature_matches" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *CodeSourceFileQuery) WithSignatureMatches(opts ...func(*CodeSignatureMatchQuery)) *CodeSourceFileQuery {
	query := (&CodeSignatureMatchClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withSignatureMatches = query
	return _q
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		Path string `json:"path,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.CodeSourceFile.Query().
//		GroupBy(codesourcefile.FieldPath).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (_q *CodeSourceFileQuery) GroupBy(field string, fields ...string) *CodeSourceFileGroupBy {
	_q.ctx.Fields = append([]string{field}, fields...)
	grbuild := &CodeSourceFileGroupBy{build: _q}
	grbuild.flds = &_q.ctx.Fields
	grbuild.label = codesourcefile.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		Path string `json:"path,omitempty"`
//	}
//
//	client.CodeSourceFile.Query().
//		Select(codesourcefile.FieldPath).
//		Scan(ctx, &v)
func (_q *CodeSourceFileQuery) Select(fields ...string) *CodeSourceFileSelect {
	_q.ctx.Fields = append(_q.ctx.Fields, fields...)
	sbuild := &CodeSourceFileSelect{CodeSourceFileQuery: _q}
	sbuild.label = codesourcefile.Label
	sbuild.flds, sbuild.scan = &_q.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a CodeSourceFileSelect configured with the given aggregations.
func (_q *CodeSourceFileQuery) Aggregate(fns ...AggregateFunc) *CodeSourceFileSelect {
	return _q.Select().Aggregate(fns...)
}

func (_q *CodeSourceFileQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range _q.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, _q); err != nil {
				return err
			}
		}
	}
	for _, f := range _q.ctx.Fields {
		if !codesourcefile.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if _q.path != nil {
		prev, err := _q.path(ctx)
		if err != nil {
			return err
		}
		_q.sql = prev
	}
	return nil
}

func (_q *CodeSourceFileQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*CodeSourceFile, error) {
	var (
		nodes       = []*CodeSourceFile{}
		_spec       = _q.querySpec()
		loadedTypes = [2]bool{
			_q.withDepsUsageEvidences != nil,
			_q.withSignatureMatches != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*CodeSourceFile).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &CodeSourceFile{config: _q.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, _q.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := _q.withDepsUsageEvidences; query != nil {
		if err := _q.loadDepsUsageEvidences(ctx, query, nodes,
			func(n *CodeSourceFile) { n.Edges.DepsUsageEvidences = []*DepsUsageEvidence{} },
			func(n *CodeSourceFile, e *DepsUsageEvidence) {
				n.Edges.DepsUsageEvidences = append(n.Edges.DepsUsageEvidences, e)
			}); err != nil {
			return nil, err
		}
	}
	if query := _q.withSignatureMatches; query != nil {
		if err := _q.loadSignatureMatches(ctx, query, nodes,
			func(n *CodeSourceFile) { n.Edges.SignatureMatches = []*CodeSignatureMatch{} },
			func(n *CodeSourceFile, e *CodeSignatureMatch) {
				n.Edges.SignatureMatches = append(n.Edges.SignatureMatches, e)
			}); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (_q *CodeSourceFileQuery) loadDepsUsageEvidences(ctx context.Context, query *DepsUsageEvidenceQuery, nodes []*CodeSourceFile, init func(*CodeSourceFile), assign func(*CodeSourceFile, *DepsUsageEvidence)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[int]*CodeSourceFile)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	query.withFKs = true
	query.Where(predicate.DepsUsageEvidence(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(codesourcefile.DepsUsageEvidencesColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.deps_usage_evidence_used_in
		if fk == nil {
			return fmt.Errorf(`foreign-key "deps_usage_evidence_used_in" is nil for node %v`, n.ID)
		}
		node, ok := nodeids[*fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "deps_usage_evidence_used_in" returned %v for node %v`, *fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}
func (_q *CodeSourceFileQuery) loadSignatureMatches(ctx context.Context, query *CodeSignatureMatchQuery, nodes []*CodeSourceFile, init func(*CodeSourceFile), assign func(*CodeSourceFile, *CodeSignatureMatch)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[int]*CodeSourceFile)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	query.withFKs = true
	query.Where(predicate.CodeSignatureMatch(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(codesourcefile.SignatureMatchesColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.code_signature_match_source_file
		if fk == nil {
			return fmt.Errorf(`foreign-key "code_signature_match_source_file" is nil for node %v`, n.ID)
		}
		node, ok := nodeids[*fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "code_signature_match_source_file" returned %v for node %v`, *fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}

func (_q *CodeSourceFileQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := _q.querySpec()
	_spec.Node.Columns = _q.ctx.Fields
	if len(_q.ctx.Fields) > 0 {
		_spec.Unique = _q.ctx.Unique != nil && *_q.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, _q.driver, _spec)
}

func (_q *CodeSourceFileQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(codesourcefile.Table, codesourcefile.Columns, sqlgraph.NewFieldSpec(codesourcefile.FieldID, field.TypeInt))
	_spec.From = _q.sql
	if unique := _q.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if _q.path != nil {
		_spec.Unique = true
	}
	if fields := _q.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, codesourcefile.FieldID)
		for i := range fields {
			if fields[i] != codesourcefile.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := _q.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := _q.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := _q.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := _q.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (_q *CodeSourceFileQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(_q.driver.Dialect())
	t1 := builder.Table(codesourcefile.Table)
	columns := _q.ctx.Fields
	if len(columns) == 0 {
		columns = codesourcefile.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if _q.sql != nil {
		selector = _q.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if _q.ctx.Unique != nil && *_q.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range _q.predicates {
		p(selector)
	}
	for _, p := range _q.order {
		p(selector)
	}
	if offset := _q.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := _q.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// CodeSourceFileGroupBy is the group-by builder for CodeSourceFile entities.
type CodeSourceFileGroupBy struct {
	selector
	build *CodeSourceFileQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (_g *CodeSourceFileGroupBy) Aggregate(fns ...AggregateFunc) *CodeSourceFileGroupBy {
	_g.fns = append(_g.fns, fns...)
	return _g
}

// Scan applies the selector query and scans the result into the given value.
func (_g *CodeSourceFileGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _g.build.ctx, ent.OpQueryGroupBy)
	if err := _g.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*CodeSourceFileQuery, *CodeSourceFileGroupBy](ctx, _g.build, _g, _g.build.inters, v)
}

func (_g *CodeSourceFileGroupBy) sqlScan(ctx context.Context, root *CodeSourceFileQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(_g.fns))
	for _, fn := range _g.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*_g.flds)+len(_g.fns))
		for _, f := range *_g.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*_g.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _g.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// CodeSourceFileSelect is the builder for selecting fields of CodeSourceFile entities.
type CodeSourceFileSelect struct {
	*CodeSourceFileQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (_s *CodeSourceFileSelect) Aggregate(fns ...AggregateFunc) *CodeSourceFileSelect {
	_s.fns = append(_s.fns, fns...)
	return _s
}

// Scan applies the selector query and scans the result into the given value.
func (_s *CodeSourceFileSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _s.ctx, ent.OpQuerySelect)
	if err := _s.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*CodeSourceFileQuery, *CodeSourceFileSelect](ctx, _s.CodeSourceFileQuery, _s, _s.inters, v)
}

func (_s *CodeSourceFileSelect) sqlScan(ctx context.Context, root *CodeSourceFileQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(_s.fns))
	for _, fn := range _s.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*_s.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _s.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
