// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/safedep/vet/ent/reportpackage"
	"github.com/safedep/vet/ent/reportpackagemanifest"
)

// ReportPackageManifestCreate is the builder for creating a ReportPackageManifest entity.
type ReportPackageManifestCreate struct {
	config
	mutation *ReportPackageManifestMutation
	hooks    []Hook
}

// SetManifestID sets the "manifest_id" field.
func (_c *ReportPackageManifestCreate) SetManifestID(v string) *ReportPackageManifestCreate {
	_c.mutation.SetManifestID(v)
	return _c
}

// SetSourceType sets the "source_type" field.
func (_c *ReportPackageManifestCreate) SetSourceType(v string) *ReportPackageManifestCreate {
	_c.mutation.SetSourceType(v)
	return _c
}

// SetNamespace sets the "namespace" field.
func (_c *ReportPackageManifestCreate) SetNamespace(v string) *ReportPackageManifestCreate {
	_c.mutation.SetNamespace(v)
	return _c
}

// SetPath sets the "path" field.
func (_c *ReportPackageManifestCreate) SetPath(v string) *ReportPackageManifestCreate {
	_c.mutation.SetPath(v)
	return _c
}

// SetDisplayPath sets the "display_path" field.
func (_c *ReportPackageManifestCreate) SetDisplayPath(v string) *ReportPackageManifestCreate {
	_c.mutation.SetDisplayPath(v)
	return _c
}

// SetEcosystem sets the "ecosystem" field.
func (_c *ReportPackageManifestCreate) SetEcosystem(v string) *ReportPackageManifestCreate {
	_c.mutation.SetEcosystem(v)
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *ReportPackageManifestCreate) SetCreatedAt(v time.Time) *ReportPackageManifestCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *ReportPackageManifestCreate) SetNillableCreatedAt(v *time.Time) *ReportPackageManifestCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *ReportPackageManifestCreate) SetUpdatedAt(v time.Time) *ReportPackageManifestCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *ReportPackageManifestCreate) SetNillableUpdatedAt(v *time.Time) *ReportPackageManifestCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// AddPackageIDs adds the "packages" edge to the ReportPackage entity by IDs.
func (_c *ReportPackageManifestCreate) AddPackageIDs(ids ...int) *ReportPackageManifestCreate {
	_c.mutation.AddPackageIDs(ids...)
	return _c
}

// AddPackages adds the "packages" edges to the ReportPackage entity.
func (_c *ReportPackageManifestCreate) AddPackages(v ...*ReportPackage) *ReportPackageManifestCreate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddPackageIDs(ids...)
}

// Mutation returns the ReportPackageManifestMutation object of the builder.
func (_c *ReportPackageManifestCreate) Mutation() *ReportPackageManifestMutation {
	return _c.mutation
}

// Save creates the ReportPackageManifest in the database.
func (_c *ReportPackageManifestCreate) Save(ctx context.Context) (*ReportPackageManifest, error) {
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *ReportPackageManifestCreate) SaveX(ctx context.Context) *ReportPackageManifest {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ReportPackageManifestCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ReportPackageManifestCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *ReportPackageManifestCreate) check() error {
	if _, ok := _c.mutation.ManifestID(); !ok {
		return &ValidationError{Name: "manifest_id", err: errors.New(`ent: missing required field "ReportPackageManifest.manifest_id"`)}
	}
	if v, ok := _c.mutation.ManifestID(); ok {
		if err := reportpackagemanifest.ManifestIDValidator(v); err != nil {
			return &ValidationError{Name: "manifest_id", err: fmt.Errorf(`ent: validator failed for field "ReportPackageManifest.manifest_id": %w`, err)}
		}
	}
	if _, ok := _c.mutation.SourceType(); !ok {
		return &ValidationError{Name: "source_type", err: errors.New(`ent: missing required field "ReportPackageManifest.source_type"`)}
	}
	if v, ok := _c.mutation.SourceType(); ok {
		if err := reportpackagemanifest.SourceTypeValidator(v); err != nil {
			return &ValidationError{Name: "source_type", err: fmt.Errorf(`ent: validator failed for field "ReportPackageManifest.source_type": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Namespace(); !ok {
		return &ValidationError{Name: "namespace", err: errors.New(`ent: missing required field "ReportPackageManifest.namespace"`)}
	}
	if v, ok := _c.mutation.Namespace(); ok {
		if err := reportpackagemanifest.NamespaceValidator(v); err != nil {
			return &ValidationError{Name: "namespace", err: fmt.Errorf(`ent: validator failed for field "ReportPackageManifest.namespace": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Path(); !ok {
		return &ValidationError{Name: "path", err: errors.New(`ent: missing required field "ReportPackageManifest.path"`)}
	}
	if v, ok := _c.mutation.Path(); ok {
		if err := reportpackagemanifest.PathValidator(v); err != nil {
			return &ValidationError{Name: "path", err: fmt.Errorf(`ent: validator failed for field "ReportPackageManifest.path": %w`, err)}
		}
	}
	if _, ok := _c.mutation.DisplayPath(); !ok {
		return &ValidationError{Name: "display_path", err: errors.New(`ent: missing required field "ReportPackageManifest.display_path"`)}
	}
	if v, ok := _c.mutation.DisplayPath(); ok {
		if err := reportpackagemanifest.DisplayPathValidator(v); err != nil {
			return &ValidationError{Name: "display_path", err: fmt.Errorf(`ent: validator failed for field "ReportPackageManifest.display_path": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Ecosystem(); !ok {
		return &ValidationError{Name: "ecosystem", err: errors.New(`ent: missing required field "ReportPackageManifest.ecosystem"`)}
	}
	if v, ok := _c.mutation.Ecosystem(); ok {
		if err := reportpackagemanifest.EcosystemValidator(v); err != nil {
			return &ValidationError{Name: "ecosystem", err: fmt.Errorf(`ent: validator failed for field "ReportPackageManifest.ecosystem": %w`, err)}
		}
	}
	return nil
}

func (_c *ReportPackageManifestCreate) sqlSave(ctx context.Context) (*ReportPackageManifest, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *ReportPackageManifestCreate) createSpec() (*ReportPackageManifest, *sqlgraph.CreateSpec) {
	var (
		_node = &ReportPackageManifest{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(reportpackagemanifest.Table, sqlgraph.NewFieldSpec(reportpackagemanifest.FieldID, field.TypeInt))
	)
	if value, ok := _c.mutation.ManifestID(); ok {
		_spec.SetField(reportpackagemanifest.FieldManifestID, field.TypeString, value)
		_node.ManifestID = value
	}
	if value, ok := _c.mutation.SourceType(); ok {
		_spec.SetField(reportpackagemanifest.FieldSourceType, field.TypeString, value)
		_node.SourceType = value
	}
	if value, ok := _c.mutation.Namespace(); ok {
		_spec.SetField(reportpackagemanifest.FieldNamespace, field.TypeString, value)
		_node.Namespace = value
	}
	if value, ok := _c.mutation.Path(); ok {
		_spec.SetField(reportpackagemanifest.FieldPath, field.TypeString, value)
		_node.Path = value
	}
	if value, ok := _c.mutation.DisplayPath(); ok {
		_spec.SetField(reportpackagemanifest.FieldDisplayPath, field.TypeString, value)
		_node.DisplayPath = value
	}
	if value, ok := _c.mutation.Ecosystem(); ok {
		_spec.SetField(reportpackagemanifest.FieldEcosystem, field.TypeString, value)
		_node.Ecosystem = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(reportpackagemanifest.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(reportpackagemanifest.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if nodes := _c.mutation.PackagesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   reportpackagemanifest.PackagesTable,
			Columns: reportpackagemanifest.PackagesPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(reportpackage.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// ReportPackageManifestCreateBulk is the builder for creating many ReportPackageManifest entities in bulk.
type ReportPackageManifestCreateBulk struct {
	config
	err      error
	builders []*ReportPackageManifestCreate
}

// Save creates the ReportPackageManifest entities in the database.
func (_c *ReportPackageManifestCreateBulk) Save(ctx context.Context) ([]*ReportPackageManifest, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*ReportPackageManifest, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*ReportPackageManifestMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *ReportPackageManifestCreateBulk) SaveX(ctx context.Context) []*ReportPackageManifest {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ReportPackageManifestCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ReportPackageManifestCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
