// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/safedep/vet/ent/reportpackage"
	"github.com/safedep/vet/ent/reportproject"
	"github.com/safedep/vet/ent/reportscorecard"
)

// ReportProject is the model entity for the ReportProject schema.
type ReportProject struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// Name holds the value of the "name" field.
	Name string `json:"name,omitempty"`
	// URL holds the value of the "url" field.
	URL string `json:"url,omitempty"`
	// Description holds the value of the "description" field.
	Description string `json:"description,omitempty"`
	// Stars holds the value of the "stars" field.
	Stars int32 `json:"stars,omitempty"`
	// Forks holds the value of the "forks" field.
	Forks int32 `json:"forks,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the ReportProjectQuery when eager-loading is set.
	Edges                   ReportProjectEdges `json:"edges"`
	report_package_projects *int
	selectValues            sql.SelectValues
}

// ReportProjectEdges holds the relations/edges for other nodes in the graph.
type ReportProjectEdges struct {
	// Package holds the value of the package edge.
	Package *ReportPackage `json:"package,omitempty"`
	// Scorecard holds the value of the scorecard edge.
	Scorecard *ReportScorecard `json:"scorecard,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [2]bool
}

// PackageOrErr returns the Package value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e ReportProjectEdges) PackageOrErr() (*ReportPackage, error) {
	if e.Package != nil {
		return e.Package, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: reportpackage.Label}
	}
	return nil, &NotLoadedError{edge: "package"}
}

// ScorecardOrErr returns the Scorecard value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e ReportProjectEdges) ScorecardOrErr() (*ReportScorecard, error) {
	if e.Scorecard != nil {
		return e.Scorecard, nil
	} else if e.loadedTypes[1] {
		return nil, &NotFoundError{label: reportscorecard.Label}
	}
	return nil, &NotLoadedError{edge: "scorecard"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*ReportProject) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case reportproject.FieldID, reportproject.FieldStars, reportproject.FieldForks:
			values[i] = new(sql.NullInt64)
		case reportproject.FieldName, reportproject.FieldURL, reportproject.FieldDescription:
			values[i] = new(sql.NullString)
		case reportproject.FieldCreatedAt, reportproject.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		case reportproject.ForeignKeys[0]: // report_package_projects
			values[i] = new(sql.NullInt64)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the ReportProject fields.
func (_m *ReportProject) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case reportproject.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case reportproject.FieldName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field name", values[i])
			} else if value.Valid {
				_m.Name = value.String
			}
		case reportproject.FieldURL:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field url", values[i])
			} else if value.Valid {
				_m.URL = value.String
			}
		case reportproject.FieldDescription:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field description", values[i])
			} else if value.Valid {
				_m.Description = value.String
			}
		case reportproject.FieldStars:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field stars", values[i])
			} else if value.Valid {
				_m.Stars = int32(value.Int64)
			}
		case reportproject.FieldForks:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field forks", values[i])
			} else if value.Valid {
				_m.Forks = int32(value.Int64)
			}
		case reportproject.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case reportproject.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		case reportproject.ForeignKeys[0]:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for edge-field report_package_projects", value)
			} else if value.Valid {
				_m.report_package_projects = new(int)
				*_m.report_package_projects = int(value.Int64)
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the ReportProject.
// This includes values selected through modifiers, order, etc.
func (_m *ReportProject) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryPackage queries the "package" edge of the ReportProject entity.
func (_m *ReportProject) QueryPackage() *ReportPackageQuery {
	return NewReportProjectClient(_m.config).QueryPackage(_m)
}

// QueryScorecard queries the "scorecard" edge of the ReportProject entity.
func (_m *ReportProject) QueryScorecard() *ReportScorecardQuery {
	return NewReportProjectClient(_m.config).QueryScorecard(_m)
}

// Update returns a builder for updating this ReportProject.
// Note that you need to call ReportProject.Unwrap() before calling this method if this ReportProject
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *ReportProject) Update() *ReportProjectUpdateOne {
	return NewReportProjectClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the ReportProject entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *ReportProject) Unwrap() *ReportProject {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: ReportProject is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *ReportProject) String() string {
	var builder strings.Builder
	builder.WriteString("ReportProject(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("name=")
	builder.WriteString(_m.Name)
	builder.WriteString(", ")
	builder.WriteString("url=")
	builder.WriteString(_m.URL)
	builder.WriteString(", ")
	builder.WriteString("description=")
	builder.WriteString(_m.Description)
	builder.WriteString(", ")
	builder.WriteString("stars=")
	builder.WriteString(fmt.Sprintf("%v", _m.Stars))
	builder.WriteString(", ")
	builder.WriteString("forks=")
	builder.WriteString(fmt.Sprintf("%v", _m.Forks))
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// ReportProjects is a parsable slice of ReportProject.
type ReportProjects []*ReportProject
