// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"database/sql/driver"
	"fmt"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/safedep/vet/ent/predicate"
	"github.com/safedep/vet/ent/reportproject"
	"github.com/safedep/vet/ent/reportscorecard"
	"github.com/safedep/vet/ent/reportscorecardcheck"
)

// ReportScorecardQuery is the builder for querying ReportScorecard entities.
type ReportScorecardQuery struct {
	config
	ctx         *QueryContext
	order       []reportscorecard.OrderOption
	inters      []Interceptor
	predicates  []predicate.ReportScorecard
	withProject *ReportProjectQuery
	withChecks  *ReportScorecardCheckQuery
	withFKs     bool
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the ReportScorecardQuery builder.
func (rsq *ReportScorecardQuery) Where(ps ...predicate.ReportScorecard) *ReportScorecardQuery {
	rsq.predicates = append(rsq.predicates, ps...)
	return rsq
}

// Limit the number of records to be returned by this query.
func (rsq *ReportScorecardQuery) Limit(limit int) *ReportScorecardQuery {
	rsq.ctx.Limit = &limit
	return rsq
}

// Offset to start from.
func (rsq *ReportScorecardQuery) Offset(offset int) *ReportScorecardQuery {
	rsq.ctx.Offset = &offset
	return rsq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (rsq *ReportScorecardQuery) Unique(unique bool) *ReportScorecardQuery {
	rsq.ctx.Unique = &unique
	return rsq
}

// Order specifies how the records should be ordered.
func (rsq *ReportScorecardQuery) Order(o ...reportscorecard.OrderOption) *ReportScorecardQuery {
	rsq.order = append(rsq.order, o...)
	return rsq
}

// QueryProject chains the current query on the "project" edge.
func (rsq *ReportScorecardQuery) QueryProject() *ReportProjectQuery {
	query := (&ReportProjectClient{config: rsq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := rsq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := rsq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(reportscorecard.Table, reportscorecard.FieldID, selector),
			sqlgraph.To(reportproject.Table, reportproject.FieldID),
			sqlgraph.Edge(sqlgraph.O2O, true, reportscorecard.ProjectTable, reportscorecard.ProjectColumn),
		)
		fromU = sqlgraph.SetNeighbors(rsq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryChecks chains the current query on the "checks" edge.
func (rsq *ReportScorecardQuery) QueryChecks() *ReportScorecardCheckQuery {
	query := (&ReportScorecardCheckClient{config: rsq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := rsq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := rsq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(reportscorecard.Table, reportscorecard.FieldID, selector),
			sqlgraph.To(reportscorecardcheck.Table, reportscorecardcheck.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, reportscorecard.ChecksTable, reportscorecard.ChecksColumn),
		)
		fromU = sqlgraph.SetNeighbors(rsq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first ReportScorecard entity from the query.
// Returns a *NotFoundError when no ReportScorecard was found.
func (rsq *ReportScorecardQuery) First(ctx context.Context) (*ReportScorecard, error) {
	nodes, err := rsq.Limit(1).All(setContextOp(ctx, rsq.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{reportscorecard.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (rsq *ReportScorecardQuery) FirstX(ctx context.Context) *ReportScorecard {
	node, err := rsq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first ReportScorecard ID from the query.
// Returns a *NotFoundError when no ReportScorecard ID was found.
func (rsq *ReportScorecardQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = rsq.Limit(1).IDs(setContextOp(ctx, rsq.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{reportscorecard.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (rsq *ReportScorecardQuery) FirstIDX(ctx context.Context) int {
	id, err := rsq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single ReportScorecard entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one ReportScorecard entity is found.
// Returns a *NotFoundError when no ReportScorecard entities are found.
func (rsq *ReportScorecardQuery) Only(ctx context.Context) (*ReportScorecard, error) {
	nodes, err := rsq.Limit(2).All(setContextOp(ctx, rsq.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{reportscorecard.Label}
	default:
		return nil, &NotSingularError{reportscorecard.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (rsq *ReportScorecardQuery) OnlyX(ctx context.Context) *ReportScorecard {
	node, err := rsq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only ReportScorecard ID in the query.
// Returns a *NotSingularError when more than one ReportScorecard ID is found.
// Returns a *NotFoundError when no entities are found.
func (rsq *ReportScorecardQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = rsq.Limit(2).IDs(setContextOp(ctx, rsq.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{reportscorecard.Label}
	default:
		err = &NotSingularError{reportscorecard.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (rsq *ReportScorecardQuery) OnlyIDX(ctx context.Context) int {
	id, err := rsq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of ReportScorecards.
func (rsq *ReportScorecardQuery) All(ctx context.Context) ([]*ReportScorecard, error) {
	ctx = setContextOp(ctx, rsq.ctx, ent.OpQueryAll)
	if err := rsq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*ReportScorecard, *ReportScorecardQuery]()
	return withInterceptors[[]*ReportScorecard](ctx, rsq, qr, rsq.inters)
}

// AllX is like All, but panics if an error occurs.
func (rsq *ReportScorecardQuery) AllX(ctx context.Context) []*ReportScorecard {
	nodes, err := rsq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of ReportScorecard IDs.
func (rsq *ReportScorecardQuery) IDs(ctx context.Context) (ids []int, err error) {
	if rsq.ctx.Unique == nil && rsq.path != nil {
		rsq.Unique(true)
	}
	ctx = setContextOp(ctx, rsq.ctx, ent.OpQueryIDs)
	if err = rsq.Select(reportscorecard.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (rsq *ReportScorecardQuery) IDsX(ctx context.Context) []int {
	ids, err := rsq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (rsq *ReportScorecardQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, rsq.ctx, ent.OpQueryCount)
	if err := rsq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, rsq, querierCount[*ReportScorecardQuery](), rsq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (rsq *ReportScorecardQuery) CountX(ctx context.Context) int {
	count, err := rsq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (rsq *ReportScorecardQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, rsq.ctx, ent.OpQueryExist)
	switch _, err := rsq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (rsq *ReportScorecardQuery) ExistX(ctx context.Context) bool {
	exist, err := rsq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the ReportScorecardQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (rsq *ReportScorecardQuery) Clone() *ReportScorecardQuery {
	if rsq == nil {
		return nil
	}
	return &ReportScorecardQuery{
		config:      rsq.config,
		ctx:         rsq.ctx.Clone(),
		order:       append([]reportscorecard.OrderOption{}, rsq.order...),
		inters:      append([]Interceptor{}, rsq.inters...),
		predicates:  append([]predicate.ReportScorecard{}, rsq.predicates...),
		withProject: rsq.withProject.Clone(),
		withChecks:  rsq.withChecks.Clone(),
		// clone intermediate query.
		sql:  rsq.sql.Clone(),
		path: rsq.path,
	}
}

// WithProject tells the query-builder to eager-load the nodes that are connected to
// the "project" edge. The optional arguments are used to configure the query builder of the edge.
func (rsq *ReportScorecardQuery) WithProject(opts ...func(*ReportProjectQuery)) *ReportScorecardQuery {
	query := (&ReportProjectClient{config: rsq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	rsq.withProject = query
	return rsq
}

// WithChecks tells the query-builder to eager-load the nodes that are connected to
// the "checks" edge. The optional arguments are used to configure the query builder of the edge.
func (rsq *ReportScorecardQuery) WithChecks(opts ...func(*ReportScorecardCheckQuery)) *ReportScorecardQuery {
	query := (&ReportScorecardCheckClient{config: rsq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	rsq.withChecks = query
	return rsq
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		Score float32 `json:"score,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.ReportScorecard.Query().
//		GroupBy(reportscorecard.FieldScore).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (rsq *ReportScorecardQuery) GroupBy(field string, fields ...string) *ReportScorecardGroupBy {
	rsq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &ReportScorecardGroupBy{build: rsq}
	grbuild.flds = &rsq.ctx.Fields
	grbuild.label = reportscorecard.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		Score float32 `json:"score,omitempty"`
//	}
//
//	client.ReportScorecard.Query().
//		Select(reportscorecard.FieldScore).
//		Scan(ctx, &v)
func (rsq *ReportScorecardQuery) Select(fields ...string) *ReportScorecardSelect {
	rsq.ctx.Fields = append(rsq.ctx.Fields, fields...)
	sbuild := &ReportScorecardSelect{ReportScorecardQuery: rsq}
	sbuild.label = reportscorecard.Label
	sbuild.flds, sbuild.scan = &rsq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a ReportScorecardSelect configured with the given aggregations.
func (rsq *ReportScorecardQuery) Aggregate(fns ...AggregateFunc) *ReportScorecardSelect {
	return rsq.Select().Aggregate(fns...)
}

func (rsq *ReportScorecardQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range rsq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, rsq); err != nil {
				return err
			}
		}
	}
	for _, f := range rsq.ctx.Fields {
		if !reportscorecard.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if rsq.path != nil {
		prev, err := rsq.path(ctx)
		if err != nil {
			return err
		}
		rsq.sql = prev
	}
	return nil
}

func (rsq *ReportScorecardQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*ReportScorecard, error) {
	var (
		nodes       = []*ReportScorecard{}
		withFKs     = rsq.withFKs
		_spec       = rsq.querySpec()
		loadedTypes = [2]bool{
			rsq.withProject != nil,
			rsq.withChecks != nil,
		}
	)
	if rsq.withProject != nil {
		withFKs = true
	}
	if withFKs {
		_spec.Node.Columns = append(_spec.Node.Columns, reportscorecard.ForeignKeys...)
	}
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*ReportScorecard).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &ReportScorecard{config: rsq.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, rsq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := rsq.withProject; query != nil {
		if err := rsq.loadProject(ctx, query, nodes, nil,
			func(n *ReportScorecard, e *ReportProject) { n.Edges.Project = e }); err != nil {
			return nil, err
		}
	}
	if query := rsq.withChecks; query != nil {
		if err := rsq.loadChecks(ctx, query, nodes,
			func(n *ReportScorecard) { n.Edges.Checks = []*ReportScorecardCheck{} },
			func(n *ReportScorecard, e *ReportScorecardCheck) { n.Edges.Checks = append(n.Edges.Checks, e) }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (rsq *ReportScorecardQuery) loadProject(ctx context.Context, query *ReportProjectQuery, nodes []*ReportScorecard, init func(*ReportScorecard), assign func(*ReportScorecard, *ReportProject)) error {
	ids := make([]int, 0, len(nodes))
	nodeids := make(map[int][]*ReportScorecard)
	for i := range nodes {
		if nodes[i].report_project_scorecard == nil {
			continue
		}
		fk := *nodes[i].report_project_scorecard
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(reportproject.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "report_project_scorecard" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}
func (rsq *ReportScorecardQuery) loadChecks(ctx context.Context, query *ReportScorecardCheckQuery, nodes []*ReportScorecard, init func(*ReportScorecard), assign func(*ReportScorecard, *ReportScorecardCheck)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[int]*ReportScorecard)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	query.withFKs = true
	query.Where(predicate.ReportScorecardCheck(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(reportscorecard.ChecksColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.report_scorecard_checks
		if fk == nil {
			return fmt.Errorf(`foreign-key "report_scorecard_checks" is nil for node %v`, n.ID)
		}
		node, ok := nodeids[*fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "report_scorecard_checks" returned %v for node %v`, *fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}

func (rsq *ReportScorecardQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := rsq.querySpec()
	_spec.Node.Columns = rsq.ctx.Fields
	if len(rsq.ctx.Fields) > 0 {
		_spec.Unique = rsq.ctx.Unique != nil && *rsq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, rsq.driver, _spec)
}

func (rsq *ReportScorecardQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(reportscorecard.Table, reportscorecard.Columns, sqlgraph.NewFieldSpec(reportscorecard.FieldID, field.TypeInt))
	_spec.From = rsq.sql
	if unique := rsq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if rsq.path != nil {
		_spec.Unique = true
	}
	if fields := rsq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, reportscorecard.FieldID)
		for i := range fields {
			if fields[i] != reportscorecard.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := rsq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := rsq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := rsq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := rsq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (rsq *ReportScorecardQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(rsq.driver.Dialect())
	t1 := builder.Table(reportscorecard.Table)
	columns := rsq.ctx.Fields
	if len(columns) == 0 {
		columns = reportscorecard.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if rsq.sql != nil {
		selector = rsq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if rsq.ctx.Unique != nil && *rsq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range rsq.predicates {
		p(selector)
	}
	for _, p := range rsq.order {
		p(selector)
	}
	if offset := rsq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := rsq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// ReportScorecardGroupBy is the group-by builder for ReportScorecard entities.
type ReportScorecardGroupBy struct {
	selector
	build *ReportScorecardQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (rsgb *ReportScorecardGroupBy) Aggregate(fns ...AggregateFunc) *ReportScorecardGroupBy {
	rsgb.fns = append(rsgb.fns, fns...)
	return rsgb
}

// Scan applies the selector query and scans the result into the given value.
func (rsgb *ReportScorecardGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, rsgb.build.ctx, ent.OpQueryGroupBy)
	if err := rsgb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*ReportScorecardQuery, *ReportScorecardGroupBy](ctx, rsgb.build, rsgb, rsgb.build.inters, v)
}

func (rsgb *ReportScorecardGroupBy) sqlScan(ctx context.Context, root *ReportScorecardQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(rsgb.fns))
	for _, fn := range rsgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*rsgb.flds)+len(rsgb.fns))
		for _, f := range *rsgb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*rsgb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := rsgb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// ReportScorecardSelect is the builder for selecting fields of ReportScorecard entities.
type ReportScorecardSelect struct {
	*ReportScorecardQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (rss *ReportScorecardSelect) Aggregate(fns ...AggregateFunc) *ReportScorecardSelect {
	rss.fns = append(rss.fns, fns...)
	return rss
}

// Scan applies the selector query and scans the result into the given value.
func (rss *ReportScorecardSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, rss.ctx, ent.OpQuerySelect)
	if err := rss.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*ReportScorecardQuery, *ReportScorecardSelect](ctx, rss.ReportScorecardQuery, rss, rss.inters, v)
}

func (rss *ReportScorecardSelect) sqlScan(ctx context.Context, root *ReportScorecardQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(rss.fns))
	for _, fn := range rss.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*rss.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := rss.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
