// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/safedep/vet/ent/reportpackage"
	"github.com/safedep/vet/ent/reportslsaprovenance"
)

// ReportSlsaProvenanceCreate is the builder for creating a ReportSlsaProvenance entity.
type ReportSlsaProvenanceCreate struct {
	config
	mutation *ReportSlsaProvenanceMutation
	hooks    []Hook
}

// SetSourceRepository sets the "source_repository" field.
func (_c *ReportSlsaProvenanceCreate) SetSourceRepository(v string) *ReportSlsaProvenanceCreate {
	_c.mutation.SetSourceRepository(v)
	return _c
}

// SetCommitSha sets the "commit_sha" field.
func (_c *ReportSlsaProvenanceCreate) SetCommitSha(v string) *ReportSlsaProvenanceCreate {
	_c.mutation.SetCommitSha(v)
	return _c
}

// SetURL sets the "url" field.
func (_c *ReportSlsaProvenanceCreate) SetURL(v string) *ReportSlsaProvenanceCreate {
	_c.mutation.SetURL(v)
	return _c
}

// SetVerified sets the "verified" field.
func (_c *ReportSlsaProvenanceCreate) SetVerified(v bool) *ReportSlsaProvenanceCreate {
	_c.mutation.SetVerified(v)
	return _c
}

// SetNillableVerified sets the "verified" field if the given value is not nil.
func (_c *ReportSlsaProvenanceCreate) SetNillableVerified(v *bool) *ReportSlsaProvenanceCreate {
	if v != nil {
		_c.SetVerified(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *ReportSlsaProvenanceCreate) SetCreatedAt(v time.Time) *ReportSlsaProvenanceCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *ReportSlsaProvenanceCreate) SetNillableCreatedAt(v *time.Time) *ReportSlsaProvenanceCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *ReportSlsaProvenanceCreate) SetUpdatedAt(v time.Time) *ReportSlsaProvenanceCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *ReportSlsaProvenanceCreate) SetNillableUpdatedAt(v *time.Time) *ReportSlsaProvenanceCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetPackageID sets the "package" edge to the ReportPackage entity by ID.
func (_c *ReportSlsaProvenanceCreate) SetPackageID(id int) *ReportSlsaProvenanceCreate {
	_c.mutation.SetPackageID(id)
	return _c
}

// SetNillablePackageID sets the "package" edge to the ReportPackage entity by ID if the given value is not nil.
func (_c *ReportSlsaProvenanceCreate) SetNillablePackageID(id *int) *ReportSlsaProvenanceCreate {
	if id != nil {
		_c = _c.SetPackageID(*id)
	}
	return _c
}

// SetPackage sets the "package" edge to the ReportPackage entity.
func (_c *ReportSlsaProvenanceCreate) SetPackage(v *ReportPackage) *ReportSlsaProvenanceCreate {
	return _c.SetPackageID(v.ID)
}

// Mutation returns the ReportSlsaProvenanceMutation object of the builder.
func (_c *ReportSlsaProvenanceCreate) Mutation() *ReportSlsaProvenanceMutation {
	return _c.mutation
}

// Save creates the ReportSlsaProvenance in the database.
func (_c *ReportSlsaProvenanceCreate) Save(ctx context.Context) (*ReportSlsaProvenance, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *ReportSlsaProvenanceCreate) SaveX(ctx context.Context) *ReportSlsaProvenance {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ReportSlsaProvenanceCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ReportSlsaProvenanceCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *ReportSlsaProvenanceCreate) defaults() {
	if _, ok := _c.mutation.Verified(); !ok {
		v := reportslsaprovenance.DefaultVerified
		_c.mutation.SetVerified(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *ReportSlsaProvenanceCreate) check() error {
	if _, ok := _c.mutation.SourceRepository(); !ok {
		return &ValidationError{Name: "source_repository", err: errors.New(`ent: missing required field "ReportSlsaProvenance.source_repository"`)}
	}
	if _, ok := _c.mutation.CommitSha(); !ok {
		return &ValidationError{Name: "commit_sha", err: errors.New(`ent: missing required field "ReportSlsaProvenance.commit_sha"`)}
	}
	if _, ok := _c.mutation.URL(); !ok {
		return &ValidationError{Name: "url", err: errors.New(`ent: missing required field "ReportSlsaProvenance.url"`)}
	}
	if _, ok := _c.mutation.Verified(); !ok {
		return &ValidationError{Name: "verified", err: errors.New(`ent: missing required field "ReportSlsaProvenance.verified"`)}
	}
	return nil
}

func (_c *ReportSlsaProvenanceCreate) sqlSave(ctx context.Context) (*ReportSlsaProvenance, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *ReportSlsaProvenanceCreate) createSpec() (*ReportSlsaProvenance, *sqlgraph.CreateSpec) {
	var (
		_node = &ReportSlsaProvenance{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(reportslsaprovenance.Table, sqlgraph.NewFieldSpec(reportslsaprovenance.FieldID, field.TypeInt))
	)
	if value, ok := _c.mutation.SourceRepository(); ok {
		_spec.SetField(reportslsaprovenance.FieldSourceRepository, field.TypeString, value)
		_node.SourceRepository = value
	}
	if value, ok := _c.mutation.CommitSha(); ok {
		_spec.SetField(reportslsaprovenance.FieldCommitSha, field.TypeString, value)
		_node.CommitSha = value
	}
	if value, ok := _c.mutation.URL(); ok {
		_spec.SetField(reportslsaprovenance.FieldURL, field.TypeString, value)
		_node.URL = value
	}
	if value, ok := _c.mutation.Verified(); ok {
		_spec.SetField(reportslsaprovenance.FieldVerified, field.TypeBool, value)
		_node.Verified = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(reportslsaprovenance.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(reportslsaprovenance.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if nodes := _c.mutation.PackageIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   reportslsaprovenance.PackageTable,
			Columns: []string{reportslsaprovenance.PackageColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(reportpackage.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.report_package_slsa_provenances = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// ReportSlsaProvenanceCreateBulk is the builder for creating many ReportSlsaProvenance entities in bulk.
type ReportSlsaProvenanceCreateBulk struct {
	config
	err      error
	builders []*ReportSlsaProvenanceCreate
}

// Save creates the ReportSlsaProvenance entities in the database.
func (_c *ReportSlsaProvenanceCreateBulk) Save(ctx context.Context) ([]*ReportSlsaProvenance, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*ReportSlsaProvenance, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*ReportSlsaProvenanceMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *ReportSlsaProvenanceCreateBulk) SaveX(ctx context.Context) []*ReportSlsaProvenance {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ReportSlsaProvenanceCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ReportSlsaProvenanceCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
