// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/safedep/vet/ent/predicate"
	"github.com/safedep/vet/ent/reportdependency"
)

// ReportDependencyDelete is the builder for deleting a ReportDependency entity.
type ReportDependencyDelete struct {
	config
	hooks    []Hook
	mutation *ReportDependencyMutation
}

// Where appends a list predicates to the ReportDependencyDelete builder.
func (rdd *ReportDependencyDelete) Where(ps ...predicate.ReportDependency) *ReportDependencyDelete {
	rdd.mutation.Where(ps...)
	return rdd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (rdd *ReportDependencyDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, rdd.sqlExec, rdd.mutation, rdd.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (rdd *ReportDependencyDelete) ExecX(ctx context.Context) int {
	n, err := rdd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (rdd *ReportDependencyDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(reportdependency.Table, sqlgraph.NewFieldSpec(reportdependency.FieldID, field.TypeInt))
	if ps := rdd.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, rdd.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	rdd.mutation.done = true
	return affected, err
}

// ReportDependencyDeleteOne is the builder for deleting a single ReportDependency entity.
type ReportDependencyDeleteOne struct {
	rdd *ReportDependencyDelete
}

// Where appends a list predicates to the ReportDependencyDelete builder.
func (rddo *ReportDependencyDeleteOne) Where(ps ...predicate.ReportDependency) *ReportDependencyDeleteOne {
	rddo.rdd.mutation.Where(ps...)
	return rddo
}

// Exec executes the deletion query.
func (rddo *ReportDependencyDeleteOne) Exec(ctx context.Context) error {
	n, err := rddo.rdd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{reportdependency.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (rddo *ReportDependencyDeleteOne) ExecX(ctx context.Context) {
	if err := rddo.Exec(ctx); err != nil {
		panic(err)
	}
}
