// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/safedep/vet/ent/reportpackage"
	"github.com/safedep/vet/ent/reportslsaprovenance"
)

// ReportSlsaProvenance is the model entity for the ReportSlsaProvenance schema.
type ReportSlsaProvenance struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// Source repository URL
	SourceRepository string `json:"source_repository,omitempty"`
	// Git commit SHA
	CommitSha string `json:"commit_sha,omitempty"`
	// SLSA provenance URL
	URL string `json:"url,omitempty"`
	// Whether the provenance is verified
	Verified bool `json:"verified,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the ReportSlsaProvenanceQuery when eager-loading is set.
	Edges                           ReportSlsaProvenanceEdges `json:"edges"`
	report_package_slsa_provenances *int
	selectValues                    sql.SelectValues
}

// ReportSlsaProvenanceEdges holds the relations/edges for other nodes in the graph.
type ReportSlsaProvenanceEdges struct {
	// Package holds the value of the package edge.
	Package *ReportPackage `json:"package,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// PackageOrErr returns the Package value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e ReportSlsaProvenanceEdges) PackageOrErr() (*ReportPackage, error) {
	if e.Package != nil {
		return e.Package, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: reportpackage.Label}
	}
	return nil, &NotLoadedError{edge: "package"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*ReportSlsaProvenance) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case reportslsaprovenance.FieldVerified:
			values[i] = new(sql.NullBool)
		case reportslsaprovenance.FieldID:
			values[i] = new(sql.NullInt64)
		case reportslsaprovenance.FieldSourceRepository, reportslsaprovenance.FieldCommitSha, reportslsaprovenance.FieldURL:
			values[i] = new(sql.NullString)
		case reportslsaprovenance.FieldCreatedAt, reportslsaprovenance.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		case reportslsaprovenance.ForeignKeys[0]: // report_package_slsa_provenances
			values[i] = new(sql.NullInt64)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the ReportSlsaProvenance fields.
func (rsp *ReportSlsaProvenance) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case reportslsaprovenance.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			rsp.ID = int(value.Int64)
		case reportslsaprovenance.FieldSourceRepository:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field source_repository", values[i])
			} else if value.Valid {
				rsp.SourceRepository = value.String
			}
		case reportslsaprovenance.FieldCommitSha:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field commit_sha", values[i])
			} else if value.Valid {
				rsp.CommitSha = value.String
			}
		case reportslsaprovenance.FieldURL:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field url", values[i])
			} else if value.Valid {
				rsp.URL = value.String
			}
		case reportslsaprovenance.FieldVerified:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field verified", values[i])
			} else if value.Valid {
				rsp.Verified = value.Bool
			}
		case reportslsaprovenance.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				rsp.CreatedAt = value.Time
			}
		case reportslsaprovenance.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				rsp.UpdatedAt = value.Time
			}
		case reportslsaprovenance.ForeignKeys[0]:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for edge-field report_package_slsa_provenances", value)
			} else if value.Valid {
				rsp.report_package_slsa_provenances = new(int)
				*rsp.report_package_slsa_provenances = int(value.Int64)
			}
		default:
			rsp.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the ReportSlsaProvenance.
// This includes values selected through modifiers, order, etc.
func (rsp *ReportSlsaProvenance) Value(name string) (ent.Value, error) {
	return rsp.selectValues.Get(name)
}

// QueryPackage queries the "package" edge of the ReportSlsaProvenance entity.
func (rsp *ReportSlsaProvenance) QueryPackage() *ReportPackageQuery {
	return NewReportSlsaProvenanceClient(rsp.config).QueryPackage(rsp)
}

// Update returns a builder for updating this ReportSlsaProvenance.
// Note that you need to call ReportSlsaProvenance.Unwrap() before calling this method if this ReportSlsaProvenance
// was returned from a transaction, and the transaction was committed or rolled back.
func (rsp *ReportSlsaProvenance) Update() *ReportSlsaProvenanceUpdateOne {
	return NewReportSlsaProvenanceClient(rsp.config).UpdateOne(rsp)
}

// Unwrap unwraps the ReportSlsaProvenance entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (rsp *ReportSlsaProvenance) Unwrap() *ReportSlsaProvenance {
	_tx, ok := rsp.config.driver.(*txDriver)
	if !ok {
		panic("ent: ReportSlsaProvenance is not a transactional entity")
	}
	rsp.config.driver = _tx.drv
	return rsp
}

// String implements the fmt.Stringer.
func (rsp *ReportSlsaProvenance) String() string {
	var builder strings.Builder
	builder.WriteString("ReportSlsaProvenance(")
	builder.WriteString(fmt.Sprintf("id=%v, ", rsp.ID))
	builder.WriteString("source_repository=")
	builder.WriteString(rsp.SourceRepository)
	builder.WriteString(", ")
	builder.WriteString("commit_sha=")
	builder.WriteString(rsp.CommitSha)
	builder.WriteString(", ")
	builder.WriteString("url=")
	builder.WriteString(rsp.URL)
	builder.WriteString(", ")
	builder.WriteString("verified=")
	builder.WriteString(fmt.Sprintf("%v", rsp.Verified))
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(rsp.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(rsp.UpdatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// ReportSlsaProvenances is a parsable slice of ReportSlsaProvenance.
type ReportSlsaProvenances []*ReportSlsaProvenance
