// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/safedep/vet/ent/predicate"
	"github.com/safedep/vet/ent/reportproject"
)

// ReportProjectDelete is the builder for deleting a ReportProject entity.
type ReportProjectDelete struct {
	config
	hooks    []Hook
	mutation *ReportProjectMutation
}

// Where appends a list predicates to the ReportProjectDelete builder.
func (rpd *ReportProjectDelete) Where(ps ...predicate.ReportProject) *ReportProjectDelete {
	rpd.mutation.Where(ps...)
	return rpd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (rpd *ReportProjectDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, rpd.sqlExec, rpd.mutation, rpd.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (rpd *ReportProjectDelete) ExecX(ctx context.Context) int {
	n, err := rpd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (rpd *ReportProjectDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(reportproject.Table, sqlgraph.NewFieldSpec(reportproject.FieldID, field.TypeInt))
	if ps := rpd.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, rpd.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	rpd.mutation.done = true
	return affected, err
}

// ReportProjectDeleteOne is the builder for deleting a single ReportProject entity.
type ReportProjectDeleteOne struct {
	rpd *ReportProjectDelete
}

// Where appends a list predicates to the ReportProjectDelete builder.
func (rpdo *ReportProjectDeleteOne) Where(ps ...predicate.ReportProject) *ReportProjectDeleteOne {
	rpdo.rpd.mutation.Where(ps...)
	return rpdo
}

// Exec executes the deletion query.
func (rpdo *ReportProjectDeleteOne) Exec(ctx context.Context) error {
	n, err := rpdo.rpd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{reportproject.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (rpdo *ReportProjectDeleteOne) ExecX(ctx context.Context) {
	if err := rpdo.Exec(ctx); err != nil {
		panic(err)
	}
}
