// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/safedep/vet/ent/reportdependency"
	"github.com/safedep/vet/ent/reportpackage"
)

// ReportDependencyCreate is the builder for creating a ReportDependency entity.
type ReportDependencyCreate struct {
	config
	mutation *ReportDependencyMutation
	hooks    []Hook
}

// SetDependencyPackageID sets the "dependency_package_id" field.
func (_c *ReportDependencyCreate) SetDependencyPackageID(v string) *ReportDependencyCreate {
	_c.mutation.SetDependencyPackageID(v)
	return _c
}

// SetDependencyName sets the "dependency_name" field.
func (_c *ReportDependencyCreate) SetDependencyName(v string) *ReportDependencyCreate {
	_c.mutation.SetDependencyName(v)
	return _c
}

// SetDependencyVersion sets the "dependency_version" field.
func (_c *ReportDependencyCreate) SetDependencyVersion(v string) *ReportDependencyCreate {
	_c.mutation.SetDependencyVersion(v)
	return _c
}

// SetDependencyEcosystem sets the "dependency_ecosystem" field.
func (_c *ReportDependencyCreate) SetDependencyEcosystem(v string) *ReportDependencyCreate {
	_c.mutation.SetDependencyEcosystem(v)
	return _c
}

// SetDependencyType sets the "dependency_type" field.
func (_c *ReportDependencyCreate) SetDependencyType(v string) *ReportDependencyCreate {
	_c.mutation.SetDependencyType(v)
	return _c
}

// SetNillableDependencyType sets the "dependency_type" field if the given value is not nil.
func (_c *ReportDependencyCreate) SetNillableDependencyType(v *string) *ReportDependencyCreate {
	if v != nil {
		_c.SetDependencyType(*v)
	}
	return _c
}

// SetDepth sets the "depth" field.
func (_c *ReportDependencyCreate) SetDepth(v int) *ReportDependencyCreate {
	_c.mutation.SetDepth(v)
	return _c
}

// SetNillableDepth sets the "depth" field if the given value is not nil.
func (_c *ReportDependencyCreate) SetNillableDepth(v *int) *ReportDependencyCreate {
	if v != nil {
		_c.SetDepth(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *ReportDependencyCreate) SetCreatedAt(v time.Time) *ReportDependencyCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *ReportDependencyCreate) SetNillableCreatedAt(v *time.Time) *ReportDependencyCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *ReportDependencyCreate) SetUpdatedAt(v time.Time) *ReportDependencyCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *ReportDependencyCreate) SetNillableUpdatedAt(v *time.Time) *ReportDependencyCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetPackageID sets the "package" edge to the ReportPackage entity by ID.
func (_c *ReportDependencyCreate) SetPackageID(id int) *ReportDependencyCreate {
	_c.mutation.SetPackageID(id)
	return _c
}

// SetNillablePackageID sets the "package" edge to the ReportPackage entity by ID if the given value is not nil.
func (_c *ReportDependencyCreate) SetNillablePackageID(id *int) *ReportDependencyCreate {
	if id != nil {
		_c = _c.SetPackageID(*id)
	}
	return _c
}

// SetPackage sets the "package" edge to the ReportPackage entity.
func (_c *ReportDependencyCreate) SetPackage(v *ReportPackage) *ReportDependencyCreate {
	return _c.SetPackageID(v.ID)
}

// Mutation returns the ReportDependencyMutation object of the builder.
func (_c *ReportDependencyCreate) Mutation() *ReportDependencyMutation {
	return _c.mutation
}

// Save creates the ReportDependency in the database.
func (_c *ReportDependencyCreate) Save(ctx context.Context) (*ReportDependency, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *ReportDependencyCreate) SaveX(ctx context.Context) *ReportDependency {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ReportDependencyCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ReportDependencyCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *ReportDependencyCreate) defaults() {
	if _, ok := _c.mutation.Depth(); !ok {
		v := reportdependency.DefaultDepth
		_c.mutation.SetDepth(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *ReportDependencyCreate) check() error {
	if _, ok := _c.mutation.DependencyPackageID(); !ok {
		return &ValidationError{Name: "dependency_package_id", err: errors.New(`ent: missing required field "ReportDependency.dependency_package_id"`)}
	}
	if v, ok := _c.mutation.DependencyPackageID(); ok {
		if err := reportdependency.DependencyPackageIDValidator(v); err != nil {
			return &ValidationError{Name: "dependency_package_id", err: fmt.Errorf(`ent: validator failed for field "ReportDependency.dependency_package_id": %w`, err)}
		}
	}
	if _, ok := _c.mutation.DependencyName(); !ok {
		return &ValidationError{Name: "dependency_name", err: errors.New(`ent: missing required field "ReportDependency.dependency_name"`)}
	}
	if v, ok := _c.mutation.DependencyName(); ok {
		if err := reportdependency.DependencyNameValidator(v); err != nil {
			return &ValidationError{Name: "dependency_name", err: fmt.Errorf(`ent: validator failed for field "ReportDependency.dependency_name": %w`, err)}
		}
	}
	if _, ok := _c.mutation.DependencyVersion(); !ok {
		return &ValidationError{Name: "dependency_version", err: errors.New(`ent: missing required field "ReportDependency.dependency_version"`)}
	}
	if v, ok := _c.mutation.DependencyVersion(); ok {
		if err := reportdependency.DependencyVersionValidator(v); err != nil {
			return &ValidationError{Name: "dependency_version", err: fmt.Errorf(`ent: validator failed for field "ReportDependency.dependency_version": %w`, err)}
		}
	}
	if _, ok := _c.mutation.DependencyEcosystem(); !ok {
		return &ValidationError{Name: "dependency_ecosystem", err: errors.New(`ent: missing required field "ReportDependency.dependency_ecosystem"`)}
	}
	if v, ok := _c.mutation.DependencyEcosystem(); ok {
		if err := reportdependency.DependencyEcosystemValidator(v); err != nil {
			return &ValidationError{Name: "dependency_ecosystem", err: fmt.Errorf(`ent: validator failed for field "ReportDependency.dependency_ecosystem": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Depth(); !ok {
		return &ValidationError{Name: "depth", err: errors.New(`ent: missing required field "ReportDependency.depth"`)}
	}
	return nil
}

func (_c *ReportDependencyCreate) sqlSave(ctx context.Context) (*ReportDependency, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *ReportDependencyCreate) createSpec() (*ReportDependency, *sqlgraph.CreateSpec) {
	var (
		_node = &ReportDependency{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(reportdependency.Table, sqlgraph.NewFieldSpec(reportdependency.FieldID, field.TypeInt))
	)
	if value, ok := _c.mutation.DependencyPackageID(); ok {
		_spec.SetField(reportdependency.FieldDependencyPackageID, field.TypeString, value)
		_node.DependencyPackageID = value
	}
	if value, ok := _c.mutation.DependencyName(); ok {
		_spec.SetField(reportdependency.FieldDependencyName, field.TypeString, value)
		_node.DependencyName = value
	}
	if value, ok := _c.mutation.DependencyVersion(); ok {
		_spec.SetField(reportdependency.FieldDependencyVersion, field.TypeString, value)
		_node.DependencyVersion = value
	}
	if value, ok := _c.mutation.DependencyEcosystem(); ok {
		_spec.SetField(reportdependency.FieldDependencyEcosystem, field.TypeString, value)
		_node.DependencyEcosystem = value
	}
	if value, ok := _c.mutation.DependencyType(); ok {
		_spec.SetField(reportdependency.FieldDependencyType, field.TypeString, value)
		_node.DependencyType = value
	}
	if value, ok := _c.mutation.Depth(); ok {
		_spec.SetField(reportdependency.FieldDepth, field.TypeInt, value)
		_node.Depth = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(reportdependency.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(reportdependency.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if nodes := _c.mutation.PackageIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   reportdependency.PackageTable,
			Columns: []string{reportdependency.PackageColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(reportpackage.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.report_package_dependencies = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// ReportDependencyCreateBulk is the builder for creating many ReportDependency entities in bulk.
type ReportDependencyCreateBulk struct {
	config
	err      error
	builders []*ReportDependencyCreate
}

// Save creates the ReportDependency entities in the database.
func (_c *ReportDependencyCreateBulk) Save(ctx context.Context) ([]*ReportDependency, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*ReportDependency, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*ReportDependencyMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *ReportDependencyCreateBulk) SaveX(ctx context.Context) []*ReportDependency {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ReportDependencyCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ReportDependencyCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
