// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/safedep/vet/ent/predicate"
	"github.com/safedep/vet/ent/reportdependency"
	"github.com/safedep/vet/ent/reportlicense"
	"github.com/safedep/vet/ent/reportmalware"
	"github.com/safedep/vet/ent/reportpackage"
	"github.com/safedep/vet/ent/reportpackagemanifest"
	"github.com/safedep/vet/ent/reportproject"
	"github.com/safedep/vet/ent/reportslsaprovenance"
	"github.com/safedep/vet/ent/reportvulnerability"
)

// ReportPackageUpdate is the builder for updating ReportPackage entities.
type ReportPackageUpdate struct {
	config
	hooks    []Hook
	mutation *ReportPackageMutation
}

// Where appends a list predicates to the ReportPackageUpdate builder.
func (_u *ReportPackageUpdate) Where(ps ...predicate.ReportPackage) *ReportPackageUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetPackageID sets the "package_id" field.
func (_u *ReportPackageUpdate) SetPackageID(v string) *ReportPackageUpdate {
	_u.mutation.SetPackageID(v)
	return _u
}

// SetNillablePackageID sets the "package_id" field if the given value is not nil.
func (_u *ReportPackageUpdate) SetNillablePackageID(v *string) *ReportPackageUpdate {
	if v != nil {
		_u.SetPackageID(*v)
	}
	return _u
}

// SetName sets the "name" field.
func (_u *ReportPackageUpdate) SetName(v string) *ReportPackageUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *ReportPackageUpdate) SetNillableName(v *string) *ReportPackageUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetVersion sets the "version" field.
func (_u *ReportPackageUpdate) SetVersion(v string) *ReportPackageUpdate {
	_u.mutation.SetVersion(v)
	return _u
}

// SetNillableVersion sets the "version" field if the given value is not nil.
func (_u *ReportPackageUpdate) SetNillableVersion(v *string) *ReportPackageUpdate {
	if v != nil {
		_u.SetVersion(*v)
	}
	return _u
}

// SetEcosystem sets the "ecosystem" field.
func (_u *ReportPackageUpdate) SetEcosystem(v string) *ReportPackageUpdate {
	_u.mutation.SetEcosystem(v)
	return _u
}

// SetNillableEcosystem sets the "ecosystem" field if the given value is not nil.
func (_u *ReportPackageUpdate) SetNillableEcosystem(v *string) *ReportPackageUpdate {
	if v != nil {
		_u.SetEcosystem(*v)
	}
	return _u
}

// SetPackageURL sets the "package_url" field.
func (_u *ReportPackageUpdate) SetPackageURL(v string) *ReportPackageUpdate {
	_u.mutation.SetPackageURL(v)
	return _u
}

// SetNillablePackageURL sets the "package_url" field if the given value is not nil.
func (_u *ReportPackageUpdate) SetNillablePackageURL(v *string) *ReportPackageUpdate {
	if v != nil {
		_u.SetPackageURL(*v)
	}
	return _u
}

// SetDepth sets the "depth" field.
func (_u *ReportPackageUpdate) SetDepth(v int) *ReportPackageUpdate {
	_u.mutation.ResetDepth()
	_u.mutation.SetDepth(v)
	return _u
}

// SetNillableDepth sets the "depth" field if the given value is not nil.
func (_u *ReportPackageUpdate) SetNillableDepth(v *int) *ReportPackageUpdate {
	if v != nil {
		_u.SetDepth(*v)
	}
	return _u
}

// AddDepth adds value to the "depth" field.
func (_u *ReportPackageUpdate) AddDepth(v int) *ReportPackageUpdate {
	_u.mutation.AddDepth(v)
	return _u
}

// SetIsDirect sets the "is_direct" field.
func (_u *ReportPackageUpdate) SetIsDirect(v bool) *ReportPackageUpdate {
	_u.mutation.SetIsDirect(v)
	return _u
}

// SetNillableIsDirect sets the "is_direct" field if the given value is not nil.
func (_u *ReportPackageUpdate) SetNillableIsDirect(v *bool) *ReportPackageUpdate {
	if v != nil {
		_u.SetIsDirect(*v)
	}
	return _u
}

// SetIsMalware sets the "is_malware" field.
func (_u *ReportPackageUpdate) SetIsMalware(v bool) *ReportPackageUpdate {
	_u.mutation.SetIsMalware(v)
	return _u
}

// SetNillableIsMalware sets the "is_malware" field if the given value is not nil.
func (_u *ReportPackageUpdate) SetNillableIsMalware(v *bool) *ReportPackageUpdate {
	if v != nil {
		_u.SetIsMalware(*v)
	}
	return _u
}

// SetIsSuspicious sets the "is_suspicious" field.
func (_u *ReportPackageUpdate) SetIsSuspicious(v bool) *ReportPackageUpdate {
	_u.mutation.SetIsSuspicious(v)
	return _u
}

// SetNillableIsSuspicious sets the "is_suspicious" field if the given value is not nil.
func (_u *ReportPackageUpdate) SetNillableIsSuspicious(v *bool) *ReportPackageUpdate {
	if v != nil {
		_u.SetIsSuspicious(*v)
	}
	return _u
}

// SetPackageDetails sets the "package_details" field.
func (_u *ReportPackageUpdate) SetPackageDetails(v map[string]interface{}) *ReportPackageUpdate {
	_u.mutation.SetPackageDetails(v)
	return _u
}

// ClearPackageDetails clears the value of the "package_details" field.
func (_u *ReportPackageUpdate) ClearPackageDetails() *ReportPackageUpdate {
	_u.mutation.ClearPackageDetails()
	return _u
}

// SetInsightsV2 sets the "insights_v2" field.
func (_u *ReportPackageUpdate) SetInsightsV2(v map[string]interface{}) *ReportPackageUpdate {
	_u.mutation.SetInsightsV2(v)
	return _u
}

// ClearInsightsV2 clears the value of the "insights_v2" field.
func (_u *ReportPackageUpdate) ClearInsightsV2() *ReportPackageUpdate {
	_u.mutation.ClearInsightsV2()
	return _u
}

// SetCodeAnalysis sets the "code_analysis" field.
func (_u *ReportPackageUpdate) SetCodeAnalysis(v map[string]interface{}) *ReportPackageUpdate {
	_u.mutation.SetCodeAnalysis(v)
	return _u
}

// ClearCodeAnalysis clears the value of the "code_analysis" field.
func (_u *ReportPackageUpdate) ClearCodeAnalysis() *ReportPackageUpdate {
	_u.mutation.ClearCodeAnalysis()
	return _u
}

// SetCreatedAt sets the "created_at" field.
func (_u *ReportPackageUpdate) SetCreatedAt(v time.Time) *ReportPackageUpdate {
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_u *ReportPackageUpdate) SetNillableCreatedAt(v *time.Time) *ReportPackageUpdate {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// ClearCreatedAt clears the value of the "created_at" field.
func (_u *ReportPackageUpdate) ClearCreatedAt() *ReportPackageUpdate {
	_u.mutation.ClearCreatedAt()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *ReportPackageUpdate) SetUpdatedAt(v time.Time) *ReportPackageUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_u *ReportPackageUpdate) SetNillableUpdatedAt(v *time.Time) *ReportPackageUpdate {
	if v != nil {
		_u.SetUpdatedAt(*v)
	}
	return _u
}

// ClearUpdatedAt clears the value of the "updated_at" field.
func (_u *ReportPackageUpdate) ClearUpdatedAt() *ReportPackageUpdate {
	_u.mutation.ClearUpdatedAt()
	return _u
}

// AddManifestIDs adds the "manifests" edge to the ReportPackageManifest entity by IDs.
func (_u *ReportPackageUpdate) AddManifestIDs(ids ...int) *ReportPackageUpdate {
	_u.mutation.AddManifestIDs(ids...)
	return _u
}

// AddManifests adds the "manifests" edges to the ReportPackageManifest entity.
func (_u *ReportPackageUpdate) AddManifests(v ...*ReportPackageManifest) *ReportPackageUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddManifestIDs(ids...)
}

// AddVulnerabilityIDs adds the "vulnerabilities" edge to the ReportVulnerability entity by IDs.
func (_u *ReportPackageUpdate) AddVulnerabilityIDs(ids ...int) *ReportPackageUpdate {
	_u.mutation.AddVulnerabilityIDs(ids...)
	return _u
}

// AddVulnerabilities adds the "vulnerabilities" edges to the ReportVulnerability entity.
func (_u *ReportPackageUpdate) AddVulnerabilities(v ...*ReportVulnerability) *ReportPackageUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddVulnerabilityIDs(ids...)
}

// AddLicenseIDs adds the "licenses" edge to the ReportLicense entity by IDs.
func (_u *ReportPackageUpdate) AddLicenseIDs(ids ...int) *ReportPackageUpdate {
	_u.mutation.AddLicenseIDs(ids...)
	return _u
}

// AddLicenses adds the "licenses" edges to the ReportLicense entity.
func (_u *ReportPackageUpdate) AddLicenses(v ...*ReportLicense) *ReportPackageUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddLicenseIDs(ids...)
}

// AddDependencyIDs adds the "dependencies" edge to the ReportDependency entity by IDs.
func (_u *ReportPackageUpdate) AddDependencyIDs(ids ...int) *ReportPackageUpdate {
	_u.mutation.AddDependencyIDs(ids...)
	return _u
}

// AddDependencies adds the "dependencies" edges to the ReportDependency entity.
func (_u *ReportPackageUpdate) AddDependencies(v ...*ReportDependency) *ReportPackageUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddDependencyIDs(ids...)
}

// SetMalwareAnalysisID sets the "malware_analysis" edge to the ReportMalware entity by ID.
func (_u *ReportPackageUpdate) SetMalwareAnalysisID(id int) *ReportPackageUpdate {
	_u.mutation.SetMalwareAnalysisID(id)
	return _u
}

// SetNillableMalwareAnalysisID sets the "malware_analysis" edge to the ReportMalware entity by ID if the given value is not nil.
func (_u *ReportPackageUpdate) SetNillableMalwareAnalysisID(id *int) *ReportPackageUpdate {
	if id != nil {
		_u = _u.SetMalwareAnalysisID(*id)
	}
	return _u
}

// SetMalwareAnalysis sets the "malware_analysis" edge to the ReportMalware entity.
func (_u *ReportPackageUpdate) SetMalwareAnalysis(v *ReportMalware) *ReportPackageUpdate {
	return _u.SetMalwareAnalysisID(v.ID)
}

// AddProjectIDs adds the "projects" edge to the ReportProject entity by IDs.
func (_u *ReportPackageUpdate) AddProjectIDs(ids ...int) *ReportPackageUpdate {
	_u.mutation.AddProjectIDs(ids...)
	return _u
}

// AddProjects adds the "projects" edges to the ReportProject entity.
func (_u *ReportPackageUpdate) AddProjects(v ...*ReportProject) *ReportPackageUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddProjectIDs(ids...)
}

// AddSlsaProvenanceIDs adds the "slsa_provenances" edge to the ReportSlsaProvenance entity by IDs.
func (_u *ReportPackageUpdate) AddSlsaProvenanceIDs(ids ...int) *ReportPackageUpdate {
	_u.mutation.AddSlsaProvenanceIDs(ids...)
	return _u
}

// AddSlsaProvenances adds the "slsa_provenances" edges to the ReportSlsaProvenance entity.
func (_u *ReportPackageUpdate) AddSlsaProvenances(v ...*ReportSlsaProvenance) *ReportPackageUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddSlsaProvenanceIDs(ids...)
}

// Mutation returns the ReportPackageMutation object of the builder.
func (_u *ReportPackageUpdate) Mutation() *ReportPackageMutation {
	return _u.mutation
}

// ClearManifests clears all "manifests" edges to the ReportPackageManifest entity.
func (_u *ReportPackageUpdate) ClearManifests() *ReportPackageUpdate {
	_u.mutation.ClearManifests()
	return _u
}

// RemoveManifestIDs removes the "manifests" edge to ReportPackageManifest entities by IDs.
func (_u *ReportPackageUpdate) RemoveManifestIDs(ids ...int) *ReportPackageUpdate {
	_u.mutation.RemoveManifestIDs(ids...)
	return _u
}

// RemoveManifests removes "manifests" edges to ReportPackageManifest entities.
func (_u *ReportPackageUpdate) RemoveManifests(v ...*ReportPackageManifest) *ReportPackageUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveManifestIDs(ids...)
}

// ClearVulnerabilities clears all "vulnerabilities" edges to the ReportVulnerability entity.
func (_u *ReportPackageUpdate) ClearVulnerabilities() *ReportPackageUpdate {
	_u.mutation.ClearVulnerabilities()
	return _u
}

// RemoveVulnerabilityIDs removes the "vulnerabilities" edge to ReportVulnerability entities by IDs.
func (_u *ReportPackageUpdate) RemoveVulnerabilityIDs(ids ...int) *ReportPackageUpdate {
	_u.mutation.RemoveVulnerabilityIDs(ids...)
	return _u
}

// RemoveVulnerabilities removes "vulnerabilities" edges to ReportVulnerability entities.
func (_u *ReportPackageUpdate) RemoveVulnerabilities(v ...*ReportVulnerability) *ReportPackageUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveVulnerabilityIDs(ids...)
}

// ClearLicenses clears all "licenses" edges to the ReportLicense entity.
func (_u *ReportPackageUpdate) ClearLicenses() *ReportPackageUpdate {
	_u.mutation.ClearLicenses()
	return _u
}

// RemoveLicenseIDs removes the "licenses" edge to ReportLicense entities by IDs.
func (_u *ReportPackageUpdate) RemoveLicenseIDs(ids ...int) *ReportPackageUpdate {
	_u.mutation.RemoveLicenseIDs(ids...)
	return _u
}

// RemoveLicenses removes "licenses" edges to ReportLicense entities.
func (_u *ReportPackageUpdate) RemoveLicenses(v ...*ReportLicense) *ReportPackageUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveLicenseIDs(ids...)
}

// ClearDependencies clears all "dependencies" edges to the ReportDependency entity.
func (_u *ReportPackageUpdate) ClearDependencies() *ReportPackageUpdate {
	_u.mutation.ClearDependencies()
	return _u
}

// RemoveDependencyIDs removes the "dependencies" edge to ReportDependency entities by IDs.
func (_u *ReportPackageUpdate) RemoveDependencyIDs(ids ...int) *ReportPackageUpdate {
	_u.mutation.RemoveDependencyIDs(ids...)
	return _u
}

// RemoveDependencies removes "dependencies" edges to ReportDependency entities.
func (_u *ReportPackageUpdate) RemoveDependencies(v ...*ReportDependency) *ReportPackageUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveDependencyIDs(ids...)
}

// ClearMalwareAnalysis clears the "malware_analysis" edge to the ReportMalware entity.
func (_u *ReportPackageUpdate) ClearMalwareAnalysis() *ReportPackageUpdate {
	_u.mutation.ClearMalwareAnalysis()
	return _u
}

// ClearProjects clears all "projects" edges to the ReportProject entity.
func (_u *ReportPackageUpdate) ClearProjects() *ReportPackageUpdate {
	_u.mutation.ClearProjects()
	return _u
}

// RemoveProjectIDs removes the "projects" edge to ReportProject entities by IDs.
func (_u *ReportPackageUpdate) RemoveProjectIDs(ids ...int) *ReportPackageUpdate {
	_u.mutation.RemoveProjectIDs(ids...)
	return _u
}

// RemoveProjects removes "projects" edges to ReportProject entities.
func (_u *ReportPackageUpdate) RemoveProjects(v ...*ReportProject) *ReportPackageUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveProjectIDs(ids...)
}

// ClearSlsaProvenances clears all "slsa_provenances" edges to the ReportSlsaProvenance entity.
func (_u *ReportPackageUpdate) ClearSlsaProvenances() *ReportPackageUpdate {
	_u.mutation.ClearSlsaProvenances()
	return _u
}

// RemoveSlsaProvenanceIDs removes the "slsa_provenances" edge to ReportSlsaProvenance entities by IDs.
func (_u *ReportPackageUpdate) RemoveSlsaProvenanceIDs(ids ...int) *ReportPackageUpdate {
	_u.mutation.RemoveSlsaProvenanceIDs(ids...)
	return _u
}

// RemoveSlsaProvenances removes "slsa_provenances" edges to ReportSlsaProvenance entities.
func (_u *ReportPackageUpdate) RemoveSlsaProvenances(v ...*ReportSlsaProvenance) *ReportPackageUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveSlsaProvenanceIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *ReportPackageUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ReportPackageUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *ReportPackageUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ReportPackageUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ReportPackageUpdate) check() error {
	if v, ok := _u.mutation.PackageID(); ok {
		if err := reportpackage.PackageIDValidator(v); err != nil {
			return &ValidationError{Name: "package_id", err: fmt.Errorf(`ent: validator failed for field "ReportPackage.package_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Name(); ok {
		if err := reportpackage.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "ReportPackage.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Version(); ok {
		if err := reportpackage.VersionValidator(v); err != nil {
			return &ValidationError{Name: "version", err: fmt.Errorf(`ent: validator failed for field "ReportPackage.version": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Ecosystem(); ok {
		if err := reportpackage.EcosystemValidator(v); err != nil {
			return &ValidationError{Name: "ecosystem", err: fmt.Errorf(`ent: validator failed for field "ReportPackage.ecosystem": %w`, err)}
		}
	}
	if v, ok := _u.mutation.PackageURL(); ok {
		if err := reportpackage.PackageURLValidator(v); err != nil {
			return &ValidationError{Name: "package_url", err: fmt.Errorf(`ent: validator failed for field "ReportPackage.package_url": %w`, err)}
		}
	}
	return nil
}

func (_u *ReportPackageUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(reportpackage.Table, reportpackage.Columns, sqlgraph.NewFieldSpec(reportpackage.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.PackageID(); ok {
		_spec.SetField(reportpackage.FieldPackageID, field.TypeString, value)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(reportpackage.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Version(); ok {
		_spec.SetField(reportpackage.FieldVersion, field.TypeString, value)
	}
	if value, ok := _u.mutation.Ecosystem(); ok {
		_spec.SetField(reportpackage.FieldEcosystem, field.TypeString, value)
	}
	if value, ok := _u.mutation.PackageURL(); ok {
		_spec.SetField(reportpackage.FieldPackageURL, field.TypeString, value)
	}
	if value, ok := _u.mutation.Depth(); ok {
		_spec.SetField(reportpackage.FieldDepth, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedDepth(); ok {
		_spec.AddField(reportpackage.FieldDepth, field.TypeInt, value)
	}
	if value, ok := _u.mutation.IsDirect(); ok {
		_spec.SetField(reportpackage.FieldIsDirect, field.TypeBool, value)
	}
	if value, ok := _u.mutation.IsMalware(); ok {
		_spec.SetField(reportpackage.FieldIsMalware, field.TypeBool, value)
	}
	if value, ok := _u.mutation.IsSuspicious(); ok {
		_spec.SetField(reportpackage.FieldIsSuspicious, field.TypeBool, value)
	}
	if value, ok := _u.mutation.PackageDetails(); ok {
		_spec.SetField(reportpackage.FieldPackageDetails, field.TypeJSON, value)
	}
	if _u.mutation.PackageDetailsCleared() {
		_spec.ClearField(reportpackage.FieldPackageDetails, field.TypeJSON)
	}
	if value, ok := _u.mutation.InsightsV2(); ok {
		_spec.SetField(reportpackage.FieldInsightsV2, field.TypeJSON, value)
	}
	if _u.mutation.InsightsV2Cleared() {
		_spec.ClearField(reportpackage.FieldInsightsV2, field.TypeJSON)
	}
	if value, ok := _u.mutation.CodeAnalysis(); ok {
		_spec.SetField(reportpackage.FieldCodeAnalysis, field.TypeJSON, value)
	}
	if _u.mutation.CodeAnalysisCleared() {
		_spec.ClearField(reportpackage.FieldCodeAnalysis, field.TypeJSON)
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(reportpackage.FieldCreatedAt, field.TypeTime, value)
	}
	if _u.mutation.CreatedAtCleared() {
		_spec.ClearField(reportpackage.FieldCreatedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(reportpackage.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.UpdatedAtCleared() {
		_spec.ClearField(reportpackage.FieldUpdatedAt, field.TypeTime)
	}
	if _u.mutation.ManifestsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   reportpackage.ManifestsTable,
			Columns: reportpackage.ManifestsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(reportpackagemanifest.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedManifestsIDs(); len(nodes) > 0 && !_u.mutation.ManifestsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   reportpackage.ManifestsTable,
			Columns: reportpackage.ManifestsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(reportpackagemanifest.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ManifestsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   reportpackage.ManifestsTable,
			Columns: reportpackage.ManifestsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(reportpackagemanifest.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.VulnerabilitiesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   reportpackage.VulnerabilitiesTable,
			Columns: []string{reportpackage.VulnerabilitiesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(reportvulnerability.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedVulnerabilitiesIDs(); len(nodes) > 0 && !_u.mutation.VulnerabilitiesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   reportpackage.VulnerabilitiesTable,
			Columns: []string{reportpackage.VulnerabilitiesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(reportvulnerability.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.VulnerabilitiesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   reportpackage.VulnerabilitiesTable,
			Columns: []string{reportpackage.VulnerabilitiesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(reportvulnerability.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.LicensesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   reportpackage.LicensesTable,
			Columns: []string{reportpackage.LicensesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(reportlicense.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedLicensesIDs(); len(nodes) > 0 && !_u.mutation.LicensesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   reportpackage.LicensesTable,
			Columns: []string{reportpackage.LicensesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(reportlicense.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.LicensesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   reportpackage.LicensesTable,
			Columns: []string{reportpackage.LicensesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(reportlicense.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.DependenciesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   reportpackage.DependenciesTable,
			Columns: []string{reportpackage.DependenciesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(reportdependency.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedDependenciesIDs(); len(nodes) > 0 && !_u.mutation.DependenciesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   reportpackage.DependenciesTable,
			Columns: []string{reportpackage.DependenciesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(reportdependency.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.DependenciesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   reportpackage.DependenciesTable,
			Columns: []string{reportpackage.DependenciesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(reportdependency.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.MalwareAnalysisCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: false,
			Table:   reportpackage.MalwareAnalysisTable,
			Columns: []string{reportpackage.MalwareAnalysisColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(reportmalware.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.MalwareAnalysisIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: false,
			Table:   reportpackage.MalwareAnalysisTable,
			Columns: []string{reportpackage.MalwareAnalysisColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(reportmalware.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.ProjectsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   reportpackage.ProjectsTable,
			Columns: []string{reportpackage.ProjectsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(reportproject.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedProjectsIDs(); len(nodes) > 0 && !_u.mutation.ProjectsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   reportpackage.ProjectsTable,
			Columns: []string{reportpackage.ProjectsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(reportproject.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ProjectsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   reportpackage.ProjectsTable,
			Columns: []string{reportpackage.ProjectsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(reportproject.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.SlsaProvenancesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   reportpackage.SlsaProvenancesTable,
			Columns: []string{reportpackage.SlsaProvenancesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(reportslsaprovenance.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedSlsaProvenancesIDs(); len(nodes) > 0 && !_u.mutation.SlsaProvenancesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   reportpackage.SlsaProvenancesTable,
			Columns: []string{reportpackage.SlsaProvenancesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(reportslsaprovenance.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.SlsaProvenancesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   reportpackage.SlsaProvenancesTable,
			Columns: []string{reportpackage.SlsaProvenancesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(reportslsaprovenance.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{reportpackage.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// ReportPackageUpdateOne is the builder for updating a single ReportPackage entity.
type ReportPackageUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *ReportPackageMutation
}

// SetPackageID sets the "package_id" field.
func (_u *ReportPackageUpdateOne) SetPackageID(v string) *ReportPackageUpdateOne {
	_u.mutation.SetPackageID(v)
	return _u
}

// SetNillablePackageID sets the "package_id" field if the given value is not nil.
func (_u *ReportPackageUpdateOne) SetNillablePackageID(v *string) *ReportPackageUpdateOne {
	if v != nil {
		_u.SetPackageID(*v)
	}
	return _u
}

// SetName sets the "name" field.
func (_u *ReportPackageUpdateOne) SetName(v string) *ReportPackageUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *ReportPackageUpdateOne) SetNillableName(v *string) *ReportPackageUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetVersion sets the "version" field.
func (_u *ReportPackageUpdateOne) SetVersion(v string) *ReportPackageUpdateOne {
	_u.mutation.SetVersion(v)
	return _u
}

// SetNillableVersion sets the "version" field if the given value is not nil.
func (_u *ReportPackageUpdateOne) SetNillableVersion(v *string) *ReportPackageUpdateOne {
	if v != nil {
		_u.SetVersion(*v)
	}
	return _u
}

// SetEcosystem sets the "ecosystem" field.
func (_u *ReportPackageUpdateOne) SetEcosystem(v string) *ReportPackageUpdateOne {
	_u.mutation.SetEcosystem(v)
	return _u
}

// SetNillableEcosystem sets the "ecosystem" field if the given value is not nil.
func (_u *ReportPackageUpdateOne) SetNillableEcosystem(v *string) *ReportPackageUpdateOne {
	if v != nil {
		_u.SetEcosystem(*v)
	}
	return _u
}

// SetPackageURL sets the "package_url" field.
func (_u *ReportPackageUpdateOne) SetPackageURL(v string) *ReportPackageUpdateOne {
	_u.mutation.SetPackageURL(v)
	return _u
}

// SetNillablePackageURL sets the "package_url" field if the given value is not nil.
func (_u *ReportPackageUpdateOne) SetNillablePackageURL(v *string) *ReportPackageUpdateOne {
	if v != nil {
		_u.SetPackageURL(*v)
	}
	return _u
}

// SetDepth sets the "depth" field.
func (_u *ReportPackageUpdateOne) SetDepth(v int) *ReportPackageUpdateOne {
	_u.mutation.ResetDepth()
	_u.mutation.SetDepth(v)
	return _u
}

// SetNillableDepth sets the "depth" field if the given value is not nil.
func (_u *ReportPackageUpdateOne) SetNillableDepth(v *int) *ReportPackageUpdateOne {
	if v != nil {
		_u.SetDepth(*v)
	}
	return _u
}

// AddDepth adds value to the "depth" field.
func (_u *ReportPackageUpdateOne) AddDepth(v int) *ReportPackageUpdateOne {
	_u.mutation.AddDepth(v)
	return _u
}

// SetIsDirect sets the "is_direct" field.
func (_u *ReportPackageUpdateOne) SetIsDirect(v bool) *ReportPackageUpdateOne {
	_u.mutation.SetIsDirect(v)
	return _u
}

// SetNillableIsDirect sets the "is_direct" field if the given value is not nil.
func (_u *ReportPackageUpdateOne) SetNillableIsDirect(v *bool) *ReportPackageUpdateOne {
	if v != nil {
		_u.SetIsDirect(*v)
	}
	return _u
}

// SetIsMalware sets the "is_malware" field.
func (_u *ReportPackageUpdateOne) SetIsMalware(v bool) *ReportPackageUpdateOne {
	_u.mutation.SetIsMalware(v)
	return _u
}

// SetNillableIsMalware sets the "is_malware" field if the given value is not nil.
func (_u *ReportPackageUpdateOne) SetNillableIsMalware(v *bool) *ReportPackageUpdateOne {
	if v != nil {
		_u.SetIsMalware(*v)
	}
	return _u
}

// SetIsSuspicious sets the "is_suspicious" field.
func (_u *ReportPackageUpdateOne) SetIsSuspicious(v bool) *ReportPackageUpdateOne {
	_u.mutation.SetIsSuspicious(v)
	return _u
}

// SetNillableIsSuspicious sets the "is_suspicious" field if the given value is not nil.
func (_u *ReportPackageUpdateOne) SetNillableIsSuspicious(v *bool) *ReportPackageUpdateOne {
	if v != nil {
		_u.SetIsSuspicious(*v)
	}
	return _u
}

// SetPackageDetails sets the "package_details" field.
func (_u *ReportPackageUpdateOne) SetPackageDetails(v map[string]interface{}) *ReportPackageUpdateOne {
	_u.mutation.SetPackageDetails(v)
	return _u
}

// ClearPackageDetails clears the value of the "package_details" field.
func (_u *ReportPackageUpdateOne) ClearPackageDetails() *ReportPackageUpdateOne {
	_u.mutation.ClearPackageDetails()
	return _u
}

// SetInsightsV2 sets the "insights_v2" field.
func (_u *ReportPackageUpdateOne) SetInsightsV2(v map[string]interface{}) *ReportPackageUpdateOne {
	_u.mutation.SetInsightsV2(v)
	return _u
}

// ClearInsightsV2 clears the value of the "insights_v2" field.
func (_u *ReportPackageUpdateOne) ClearInsightsV2() *ReportPackageUpdateOne {
	_u.mutation.ClearInsightsV2()
	return _u
}

// SetCodeAnalysis sets the "code_analysis" field.
func (_u *ReportPackageUpdateOne) SetCodeAnalysis(v map[string]interface{}) *ReportPackageUpdateOne {
	_u.mutation.SetCodeAnalysis(v)
	return _u
}

// ClearCodeAnalysis clears the value of the "code_analysis" field.
func (_u *ReportPackageUpdateOne) ClearCodeAnalysis() *ReportPackageUpdateOne {
	_u.mutation.ClearCodeAnalysis()
	return _u
}

// SetCreatedAt sets the "created_at" field.
func (_u *ReportPackageUpdateOne) SetCreatedAt(v time.Time) *ReportPackageUpdateOne {
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_u *ReportPackageUpdateOne) SetNillableCreatedAt(v *time.Time) *ReportPackageUpdateOne {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// ClearCreatedAt clears the value of the "created_at" field.
func (_u *ReportPackageUpdateOne) ClearCreatedAt() *ReportPackageUpdateOne {
	_u.mutation.ClearCreatedAt()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *ReportPackageUpdateOne) SetUpdatedAt(v time.Time) *ReportPackageUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_u *ReportPackageUpdateOne) SetNillableUpdatedAt(v *time.Time) *ReportPackageUpdateOne {
	if v != nil {
		_u.SetUpdatedAt(*v)
	}
	return _u
}

// ClearUpdatedAt clears the value of the "updated_at" field.
func (_u *ReportPackageUpdateOne) ClearUpdatedAt() *ReportPackageUpdateOne {
	_u.mutation.ClearUpdatedAt()
	return _u
}

// AddManifestIDs adds the "manifests" edge to the ReportPackageManifest entity by IDs.
func (_u *ReportPackageUpdateOne) AddManifestIDs(ids ...int) *ReportPackageUpdateOne {
	_u.mutation.AddManifestIDs(ids...)
	return _u
}

// AddManifests adds the "manifests" edges to the ReportPackageManifest entity.
func (_u *ReportPackageUpdateOne) AddManifests(v ...*ReportPackageManifest) *ReportPackageUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddManifestIDs(ids...)
}

// AddVulnerabilityIDs adds the "vulnerabilities" edge to the ReportVulnerability entity by IDs.
func (_u *ReportPackageUpdateOne) AddVulnerabilityIDs(ids ...int) *ReportPackageUpdateOne {
	_u.mutation.AddVulnerabilityIDs(ids...)
	return _u
}

// AddVulnerabilities adds the "vulnerabilities" edges to the ReportVulnerability entity.
func (_u *ReportPackageUpdateOne) AddVulnerabilities(v ...*ReportVulnerability) *ReportPackageUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddVulnerabilityIDs(ids...)
}

// AddLicenseIDs adds the "licenses" edge to the ReportLicense entity by IDs.
func (_u *ReportPackageUpdateOne) AddLicenseIDs(ids ...int) *ReportPackageUpdateOne {
	_u.mutation.AddLicenseIDs(ids...)
	return _u
}

// AddLicenses adds the "licenses" edges to the ReportLicense entity.
func (_u *ReportPackageUpdateOne) AddLicenses(v ...*ReportLicense) *ReportPackageUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddLicenseIDs(ids...)
}

// AddDependencyIDs adds the "dependencies" edge to the ReportDependency entity by IDs.
func (_u *ReportPackageUpdateOne) AddDependencyIDs(ids ...int) *ReportPackageUpdateOne {
	_u.mutation.AddDependencyIDs(ids...)
	return _u
}

// AddDependencies adds the "dependencies" edges to the ReportDependency entity.
func (_u *ReportPackageUpdateOne) AddDependencies(v ...*ReportDependency) *ReportPackageUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddDependencyIDs(ids...)
}

// SetMalwareAnalysisID sets the "malware_analysis" edge to the ReportMalware entity by ID.
func (_u *ReportPackageUpdateOne) SetMalwareAnalysisID(id int) *ReportPackageUpdateOne {
	_u.mutation.SetMalwareAnalysisID(id)
	return _u
}

// SetNillableMalwareAnalysisID sets the "malware_analysis" edge to the ReportMalware entity by ID if the given value is not nil.
func (_u *ReportPackageUpdateOne) SetNillableMalwareAnalysisID(id *int) *ReportPackageUpdateOne {
	if id != nil {
		_u = _u.SetMalwareAnalysisID(*id)
	}
	return _u
}

// SetMalwareAnalysis sets the "malware_analysis" edge to the ReportMalware entity.
func (_u *ReportPackageUpdateOne) SetMalwareAnalysis(v *ReportMalware) *ReportPackageUpdateOne {
	return _u.SetMalwareAnalysisID(v.ID)
}

// AddProjectIDs adds the "projects" edge to the ReportProject entity by IDs.
func (_u *ReportPackageUpdateOne) AddProjectIDs(ids ...int) *ReportPackageUpdateOne {
	_u.mutation.AddProjectIDs(ids...)
	return _u
}

// AddProjects adds the "projects" edges to the ReportProject entity.
func (_u *ReportPackageUpdateOne) AddProjects(v ...*ReportProject) *ReportPackageUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddProjectIDs(ids...)
}

// AddSlsaProvenanceIDs adds the "slsa_provenances" edge to the ReportSlsaProvenance entity by IDs.
func (_u *ReportPackageUpdateOne) AddSlsaProvenanceIDs(ids ...int) *ReportPackageUpdateOne {
	_u.mutation.AddSlsaProvenanceIDs(ids...)
	return _u
}

// AddSlsaProvenances adds the "slsa_provenances" edges to the ReportSlsaProvenance entity.
func (_u *ReportPackageUpdateOne) AddSlsaProvenances(v ...*ReportSlsaProvenance) *ReportPackageUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddSlsaProvenanceIDs(ids...)
}

// Mutation returns the ReportPackageMutation object of the builder.
func (_u *ReportPackageUpdateOne) Mutation() *ReportPackageMutation {
	return _u.mutation
}

// ClearManifests clears all "manifests" edges to the ReportPackageManifest entity.
func (_u *ReportPackageUpdateOne) ClearManifests() *ReportPackageUpdateOne {
	_u.mutation.ClearManifests()
	return _u
}

// RemoveManifestIDs removes the "manifests" edge to ReportPackageManifest entities by IDs.
func (_u *ReportPackageUpdateOne) RemoveManifestIDs(ids ...int) *ReportPackageUpdateOne {
	_u.mutation.RemoveManifestIDs(ids...)
	return _u
}

// RemoveManifests removes "manifests" edges to ReportPackageManifest entities.
func (_u *ReportPackageUpdateOne) RemoveManifests(v ...*ReportPackageManifest) *ReportPackageUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveManifestIDs(ids...)
}

// ClearVulnerabilities clears all "vulnerabilities" edges to the ReportVulnerability entity.
func (_u *ReportPackageUpdateOne) ClearVulnerabilities() *ReportPackageUpdateOne {
	_u.mutation.ClearVulnerabilities()
	return _u
}

// RemoveVulnerabilityIDs removes the "vulnerabilities" edge to ReportVulnerability entities by IDs.
func (_u *ReportPackageUpdateOne) RemoveVulnerabilityIDs(ids ...int) *ReportPackageUpdateOne {
	_u.mutation.RemoveVulnerabilityIDs(ids...)
	return _u
}

// RemoveVulnerabilities removes "vulnerabilities" edges to ReportVulnerability entities.
func (_u *ReportPackageUpdateOne) RemoveVulnerabilities(v ...*ReportVulnerability) *ReportPackageUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveVulnerabilityIDs(ids...)
}

// ClearLicenses clears all "licenses" edges to the ReportLicense entity.
func (_u *ReportPackageUpdateOne) ClearLicenses() *ReportPackageUpdateOne {
	_u.mutation.ClearLicenses()
	return _u
}

// RemoveLicenseIDs removes the "licenses" edge to ReportLicense entities by IDs.
func (_u *ReportPackageUpdateOne) RemoveLicenseIDs(ids ...int) *ReportPackageUpdateOne {
	_u.mutation.RemoveLicenseIDs(ids...)
	return _u
}

// RemoveLicenses removes "licenses" edges to ReportLicense entities.
func (_u *ReportPackageUpdateOne) RemoveLicenses(v ...*ReportLicense) *ReportPackageUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveLicenseIDs(ids...)
}

// ClearDependencies clears all "dependencies" edges to the ReportDependency entity.
func (_u *ReportPackageUpdateOne) ClearDependencies() *ReportPackageUpdateOne {
	_u.mutation.ClearDependencies()
	return _u
}

// RemoveDependencyIDs removes the "dependencies" edge to ReportDependency entities by IDs.
func (_u *ReportPackageUpdateOne) RemoveDependencyIDs(ids ...int) *ReportPackageUpdateOne {
	_u.mutation.RemoveDependencyIDs(ids...)
	return _u
}

// RemoveDependencies removes "dependencies" edges to ReportDependency entities.
func (_u *ReportPackageUpdateOne) RemoveDependencies(v ...*ReportDependency) *ReportPackageUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveDependencyIDs(ids...)
}

// ClearMalwareAnalysis clears the "malware_analysis" edge to the ReportMalware entity.
func (_u *ReportPackageUpdateOne) ClearMalwareAnalysis() *ReportPackageUpdateOne {
	_u.mutation.ClearMalwareAnalysis()
	return _u
}

// ClearProjects clears all "projects" edges to the ReportProject entity.
func (_u *ReportPackageUpdateOne) ClearProjects() *ReportPackageUpdateOne {
	_u.mutation.ClearProjects()
	return _u
}

// RemoveProjectIDs removes the "projects" edge to ReportProject entities by IDs.
func (_u *ReportPackageUpdateOne) RemoveProjectIDs(ids ...int) *ReportPackageUpdateOne {
	_u.mutation.RemoveProjectIDs(ids...)
	return _u
}

// RemoveProjects removes "projects" edges to ReportProject entities.
func (_u *ReportPackageUpdateOne) RemoveProjects(v ...*ReportProject) *ReportPackageUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveProjectIDs(ids...)
}

// ClearSlsaProvenances clears all "slsa_provenances" edges to the ReportSlsaProvenance entity.
func (_u *ReportPackageUpdateOne) ClearSlsaProvenances() *ReportPackageUpdateOne {
	_u.mutation.ClearSlsaProvenances()
	return _u
}

// RemoveSlsaProvenanceIDs removes the "slsa_provenances" edge to ReportSlsaProvenance entities by IDs.
func (_u *ReportPackageUpdateOne) RemoveSlsaProvenanceIDs(ids ...int) *ReportPackageUpdateOne {
	_u.mutation.RemoveSlsaProvenanceIDs(ids...)
	return _u
}

// RemoveSlsaProvenances removes "slsa_provenances" edges to ReportSlsaProvenance entities.
func (_u *ReportPackageUpdateOne) RemoveSlsaProvenances(v ...*ReportSlsaProvenance) *ReportPackageUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveSlsaProvenanceIDs(ids...)
}

// Where appends a list predicates to the ReportPackageUpdate builder.
func (_u *ReportPackageUpdateOne) Where(ps ...predicate.ReportPackage) *ReportPackageUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *ReportPackageUpdateOne) Select(field string, fields ...string) *ReportPackageUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated ReportPackage entity.
func (_u *ReportPackageUpdateOne) Save(ctx context.Context) (*ReportPackage, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ReportPackageUpdateOne) SaveX(ctx context.Context) *ReportPackage {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *ReportPackageUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ReportPackageUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ReportPackageUpdateOne) check() error {
	if v, ok := _u.mutation.PackageID(); ok {
		if err := reportpackage.PackageIDValidator(v); err != nil {
			return &ValidationError{Name: "package_id", err: fmt.Errorf(`ent: validator failed for field "ReportPackage.package_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Name(); ok {
		if err := reportpackage.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "ReportPackage.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Version(); ok {
		if err := reportpackage.VersionValidator(v); err != nil {
			return &ValidationError{Name: "version", err: fmt.Errorf(`ent: validator failed for field "ReportPackage.version": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Ecosystem(); ok {
		if err := reportpackage.EcosystemValidator(v); err != nil {
			return &ValidationError{Name: "ecosystem", err: fmt.Errorf(`ent: validator failed for field "ReportPackage.ecosystem": %w`, err)}
		}
	}
	if v, ok := _u.mutation.PackageURL(); ok {
		if err := reportpackage.PackageURLValidator(v); err != nil {
			return &ValidationError{Name: "package_url", err: fmt.Errorf(`ent: validator failed for field "ReportPackage.package_url": %w`, err)}
		}
	}
	return nil
}

func (_u *ReportPackageUpdateOne) sqlSave(ctx context.Context) (_node *ReportPackage, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(reportpackage.Table, reportpackage.Columns, sqlgraph.NewFieldSpec(reportpackage.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "ReportPackage.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, reportpackage.FieldID)
		for _, f := range fields {
			if !reportpackage.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != reportpackage.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.PackageID(); ok {
		_spec.SetField(reportpackage.FieldPackageID, field.TypeString, value)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(reportpackage.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Version(); ok {
		_spec.SetField(reportpackage.FieldVersion, field.TypeString, value)
	}
	if value, ok := _u.mutation.Ecosystem(); ok {
		_spec.SetField(reportpackage.FieldEcosystem, field.TypeString, value)
	}
	if value, ok := _u.mutation.PackageURL(); ok {
		_spec.SetField(reportpackage.FieldPackageURL, field.TypeString, value)
	}
	if value, ok := _u.mutation.Depth(); ok {
		_spec.SetField(reportpackage.FieldDepth, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedDepth(); ok {
		_spec.AddField(reportpackage.FieldDepth, field.TypeInt, value)
	}
	if value, ok := _u.mutation.IsDirect(); ok {
		_spec.SetField(reportpackage.FieldIsDirect, field.TypeBool, value)
	}
	if value, ok := _u.mutation.IsMalware(); ok {
		_spec.SetField(reportpackage.FieldIsMalware, field.TypeBool, value)
	}
	if value, ok := _u.mutation.IsSuspicious(); ok {
		_spec.SetField(reportpackage.FieldIsSuspicious, field.TypeBool, value)
	}
	if value, ok := _u.mutation.PackageDetails(); ok {
		_spec.SetField(reportpackage.FieldPackageDetails, field.TypeJSON, value)
	}
	if _u.mutation.PackageDetailsCleared() {
		_spec.ClearField(reportpackage.FieldPackageDetails, field.TypeJSON)
	}
	if value, ok := _u.mutation.InsightsV2(); ok {
		_spec.SetField(reportpackage.FieldInsightsV2, field.TypeJSON, value)
	}
	if _u.mutation.InsightsV2Cleared() {
		_spec.ClearField(reportpackage.FieldInsightsV2, field.TypeJSON)
	}
	if value, ok := _u.mutation.CodeAnalysis(); ok {
		_spec.SetField(reportpackage.FieldCodeAnalysis, field.TypeJSON, value)
	}
	if _u.mutation.CodeAnalysisCleared() {
		_spec.ClearField(reportpackage.FieldCodeAnalysis, field.TypeJSON)
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(reportpackage.FieldCreatedAt, field.TypeTime, value)
	}
	if _u.mutation.CreatedAtCleared() {
		_spec.ClearField(reportpackage.FieldCreatedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(reportpackage.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.UpdatedAtCleared() {
		_spec.ClearField(reportpackage.FieldUpdatedAt, field.TypeTime)
	}
	if _u.mutation.ManifestsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   reportpackage.ManifestsTable,
			Columns: reportpackage.ManifestsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(reportpackagemanifest.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedManifestsIDs(); len(nodes) > 0 && !_u.mutation.ManifestsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   reportpackage.ManifestsTable,
			Columns: reportpackage.ManifestsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(reportpackagemanifest.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ManifestsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   reportpackage.ManifestsTable,
			Columns: reportpackage.ManifestsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(reportpackagemanifest.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.VulnerabilitiesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   reportpackage.VulnerabilitiesTable,
			Columns: []string{reportpackage.VulnerabilitiesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(reportvulnerability.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedVulnerabilitiesIDs(); len(nodes) > 0 && !_u.mutation.VulnerabilitiesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   reportpackage.VulnerabilitiesTable,
			Columns: []string{reportpackage.VulnerabilitiesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(reportvulnerability.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.VulnerabilitiesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   reportpackage.VulnerabilitiesTable,
			Columns: []string{reportpackage.VulnerabilitiesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(reportvulnerability.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.LicensesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   reportpackage.LicensesTable,
			Columns: []string{reportpackage.LicensesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(reportlicense.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedLicensesIDs(); len(nodes) > 0 && !_u.mutation.LicensesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   reportpackage.LicensesTable,
			Columns: []string{reportpackage.LicensesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(reportlicense.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.LicensesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   reportpackage.LicensesTable,
			Columns: []string{reportpackage.LicensesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(reportlicense.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.DependenciesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   reportpackage.DependenciesTable,
			Columns: []string{reportpackage.DependenciesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(reportdependency.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedDependenciesIDs(); len(nodes) > 0 && !_u.mutation.DependenciesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   reportpackage.DependenciesTable,
			Columns: []string{reportpackage.DependenciesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(reportdependency.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.DependenciesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   reportpackage.DependenciesTable,
			Columns: []string{reportpackage.DependenciesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(reportdependency.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.MalwareAnalysisCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: false,
			Table:   reportpackage.MalwareAnalysisTable,
			Columns: []string{reportpackage.MalwareAnalysisColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(reportmalware.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.MalwareAnalysisIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: false,
			Table:   reportpackage.MalwareAnalysisTable,
			Columns: []string{reportpackage.MalwareAnalysisColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(reportmalware.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.ProjectsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   reportpackage.ProjectsTable,
			Columns: []string{reportpackage.ProjectsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(reportproject.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedProjectsIDs(); len(nodes) > 0 && !_u.mutation.ProjectsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   reportpackage.ProjectsTable,
			Columns: []string{reportpackage.ProjectsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(reportproject.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ProjectsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   reportpackage.ProjectsTable,
			Columns: []string{reportpackage.ProjectsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(reportproject.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.SlsaProvenancesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   reportpackage.SlsaProvenancesTable,
			Columns: []string{reportpackage.SlsaProvenancesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(reportslsaprovenance.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedSlsaProvenancesIDs(); len(nodes) > 0 && !_u.mutation.SlsaProvenancesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   reportpackage.SlsaProvenancesTable,
			Columns: []string{reportpackage.SlsaProvenancesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(reportslsaprovenance.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.SlsaProvenancesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   reportpackage.SlsaProvenancesTable,
			Columns: []string{reportpackage.SlsaProvenancesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(reportslsaprovenance.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &ReportPackage{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{reportpackage.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
