// Code generated by ent, DO NOT EDIT.

package codesignaturematch

import (
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/safedep/vet/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.CodeSignatureMatch {
	return predicate.CodeSignatureMatch(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.CodeSignatureMatch {
	return predicate.CodeSignatureMatch(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.CodeSignatureMatch {
	return predicate.CodeSignatureMatch(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.CodeSignatureMatch {
	return predicate.CodeSignatureMatch(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.CodeSignatureMatch {
	return predicate.CodeSignatureMatch(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.CodeSignatureMatch {
	return predicate.CodeSignatureMatch(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.CodeSignatureMatch {
	return predicate.CodeSignatureMatch(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.CodeSignatureMatch {
	return predicate.CodeSignatureMatch(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.CodeSignatureMatch {
	return predicate.CodeSignatureMatch(sql.FieldLTE(FieldID, id))
}

// SignatureID applies equality check predicate on the "signature_id" field. It's identical to SignatureIDEQ.
func SignatureID(v string) predicate.CodeSignatureMatch {
	return predicate.CodeSignatureMatch(sql.FieldEQ(FieldSignatureID, v))
}

// SignatureVendor applies equality check predicate on the "signature_vendor" field. It's identical to SignatureVendorEQ.
func SignatureVendor(v string) predicate.CodeSignatureMatch {
	return predicate.CodeSignatureMatch(sql.FieldEQ(FieldSignatureVendor, v))
}

// SignatureProduct applies equality check predicate on the "signature_product" field. It's identical to SignatureProductEQ.
func SignatureProduct(v string) predicate.CodeSignatureMatch {
	return predicate.CodeSignatureMatch(sql.FieldEQ(FieldSignatureProduct, v))
}

// SignatureService applies equality check predicate on the "signature_service" field. It's identical to SignatureServiceEQ.
func SignatureService(v string) predicate.CodeSignatureMatch {
	return predicate.CodeSignatureMatch(sql.FieldEQ(FieldSignatureService, v))
}

// SignatureDescription applies equality check predicate on the "signature_description" field. It's identical to SignatureDescriptionEQ.
func SignatureDescription(v string) predicate.CodeSignatureMatch {
	return predicate.CodeSignatureMatch(sql.FieldEQ(FieldSignatureDescription, v))
}

// FilePath applies equality check predicate on the "file_path" field. It's identical to FilePathEQ.
func FilePath(v string) predicate.CodeSignatureMatch {
	return predicate.CodeSignatureMatch(sql.FieldEQ(FieldFilePath, v))
}

// Language applies equality check predicate on the "language" field. It's identical to LanguageEQ.
func Language(v string) predicate.CodeSignatureMatch {
	return predicate.CodeSignatureMatch(sql.FieldEQ(FieldLanguage, v))
}

// Line applies equality check predicate on the "line" field. It's identical to LineEQ.
func Line(v uint) predicate.CodeSignatureMatch {
	return predicate.CodeSignatureMatch(sql.FieldEQ(FieldLine, v))
}

// Column applies equality check predicate on the "column" field. It's identical to ColumnEQ.
func Column(v uint) predicate.CodeSignatureMatch {
	return predicate.CodeSignatureMatch(sql.FieldEQ(FieldColumn, v))
}

// CalleeNamespace applies equality check predicate on the "callee_namespace" field. It's identical to CalleeNamespaceEQ.
func CalleeNamespace(v string) predicate.CodeSignatureMatch {
	return predicate.CodeSignatureMatch(sql.FieldEQ(FieldCalleeNamespace, v))
}

// MatchedCall applies equality check predicate on the "matched_call" field. It's identical to MatchedCallEQ.
func MatchedCall(v string) predicate.CodeSignatureMatch {
	return predicate.CodeSignatureMatch(sql.FieldEQ(FieldMatchedCall, v))
}

// PackageHint applies equality check predicate on the "package_hint" field. It's identical to PackageHintEQ.
func PackageHint(v string) predicate.CodeSignatureMatch {
	return predicate.CodeSignatureMatch(sql.FieldEQ(FieldPackageHint, v))
}

// SignatureIDEQ applies the EQ predicate on the "signature_id" field.
func SignatureIDEQ(v string) predicate.CodeSignatureMatch {
	return predicate.CodeSignatureMatch(sql.FieldEQ(FieldSignatureID, v))
}

// SignatureIDNEQ applies the NEQ predicate on the "signature_id" field.
func SignatureIDNEQ(v string) predicate.CodeSignatureMatch {
	return predicate.CodeSignatureMatch(sql.FieldNEQ(FieldSignatureID, v))
}

// SignatureIDIn applies the In predicate on the "signature_id" field.
func SignatureIDIn(vs ...string) predicate.CodeSignatureMatch {
	return predicate.CodeSignatureMatch(sql.FieldIn(FieldSignatureID, vs...))
}

// SignatureIDNotIn applies the NotIn predicate on the "signature_id" field.
func SignatureIDNotIn(vs ...string) predicate.CodeSignatureMatch {
	return predicate.CodeSignatureMatch(sql.FieldNotIn(FieldSignatureID, vs...))
}

// SignatureIDGT applies the GT predicate on the "signature_id" field.
func SignatureIDGT(v string) predicate.CodeSignatureMatch {
	return predicate.CodeSignatureMatch(sql.FieldGT(FieldSignatureID, v))
}

// SignatureIDGTE applies the GTE predicate on the "signature_id" field.
func SignatureIDGTE(v string) predicate.CodeSignatureMatch {
	return predicate.CodeSignatureMatch(sql.FieldGTE(FieldSignatureID, v))
}

// SignatureIDLT applies the LT predicate on the "signature_id" field.
func SignatureIDLT(v string) predicate.CodeSignatureMatch {
	return predicate.CodeSignatureMatch(sql.FieldLT(FieldSignatureID, v))
}

// SignatureIDLTE applies the LTE predicate on the "signature_id" field.
func SignatureIDLTE(v string) predicate.CodeSignatureMatch {
	return predicate.CodeSignatureMatch(sql.FieldLTE(FieldSignatureID, v))
}

// SignatureIDContains applies the Contains predicate on the "signature_id" field.
func SignatureIDContains(v string) predicate.CodeSignatureMatch {
	return predicate.CodeSignatureMatch(sql.FieldContains(FieldSignatureID, v))
}

// SignatureIDHasPrefix applies the HasPrefix predicate on the "signature_id" field.
func SignatureIDHasPrefix(v string) predicate.CodeSignatureMatch {
	return predicate.CodeSignatureMatch(sql.FieldHasPrefix(FieldSignatureID, v))
}

// SignatureIDHasSuffix applies the HasSuffix predicate on the "signature_id" field.
func SignatureIDHasSuffix(v string) predicate.CodeSignatureMatch {
	return predicate.CodeSignatureMatch(sql.FieldHasSuffix(FieldSignatureID, v))
}

// SignatureIDEqualFold applies the EqualFold predicate on the "signature_id" field.
func SignatureIDEqualFold(v string) predicate.CodeSignatureMatch {
	return predicate.CodeSignatureMatch(sql.FieldEqualFold(FieldSignatureID, v))
}

// SignatureIDContainsFold applies the ContainsFold predicate on the "signature_id" field.
func SignatureIDContainsFold(v string) predicate.CodeSignatureMatch {
	return predicate.CodeSignatureMatch(sql.FieldContainsFold(FieldSignatureID, v))
}

// SignatureVendorEQ applies the EQ predicate on the "signature_vendor" field.
func SignatureVendorEQ(v string) predicate.CodeSignatureMatch {
	return predicate.CodeSignatureMatch(sql.FieldEQ(FieldSignatureVendor, v))
}

// SignatureVendorNEQ applies the NEQ predicate on the "signature_vendor" field.
func SignatureVendorNEQ(v string) predicate.CodeSignatureMatch {
	return predicate.CodeSignatureMatch(sql.FieldNEQ(FieldSignatureVendor, v))
}

// SignatureVendorIn applies the In predicate on the "signature_vendor" field.
func SignatureVendorIn(vs ...string) predicate.CodeSignatureMatch {
	return predicate.CodeSignatureMatch(sql.FieldIn(FieldSignatureVendor, vs...))
}

// SignatureVendorNotIn applies the NotIn predicate on the "signature_vendor" field.
func SignatureVendorNotIn(vs ...string) predicate.CodeSignatureMatch {
	return predicate.CodeSignatureMatch(sql.FieldNotIn(FieldSignatureVendor, vs...))
}

// SignatureVendorGT applies the GT predicate on the "signature_vendor" field.
func SignatureVendorGT(v string) predicate.CodeSignatureMatch {
	return predicate.CodeSignatureMatch(sql.FieldGT(FieldSignatureVendor, v))
}

// SignatureVendorGTE applies the GTE predicate on the "signature_vendor" field.
func SignatureVendorGTE(v string) predicate.CodeSignatureMatch {
	return predicate.CodeSignatureMatch(sql.FieldGTE(FieldSignatureVendor, v))
}

// SignatureVendorLT applies the LT predicate on the "signature_vendor" field.
func SignatureVendorLT(v string) predicate.CodeSignatureMatch {
	return predicate.CodeSignatureMatch(sql.FieldLT(FieldSignatureVendor, v))
}

// SignatureVendorLTE applies the LTE predicate on the "signature_vendor" field.
func SignatureVendorLTE(v string) predicate.CodeSignatureMatch {
	return predicate.CodeSignatureMatch(sql.FieldLTE(FieldSignatureVendor, v))
}

// SignatureVendorContains applies the Contains predicate on the "signature_vendor" field.
func SignatureVendorContains(v string) predicate.CodeSignatureMatch {
	return predicate.CodeSignatureMatch(sql.FieldContains(FieldSignatureVendor, v))
}

// SignatureVendorHasPrefix applies the HasPrefix predicate on the "signature_vendor" field.
func SignatureVendorHasPrefix(v string) predicate.CodeSignatureMatch {
	return predicate.CodeSignatureMatch(sql.FieldHasPrefix(FieldSignatureVendor, v))
}

// SignatureVendorHasSuffix applies the HasSuffix predicate on the "signature_vendor" field.
func SignatureVendorHasSuffix(v string) predicate.CodeSignatureMatch {
	return predicate.CodeSignatureMatch(sql.FieldHasSuffix(FieldSignatureVendor, v))
}

// SignatureVendorIsNil applies the IsNil predicate on the "signature_vendor" field.
func SignatureVendorIsNil() predicate.CodeSignatureMatch {
	return predicate.CodeSignatureMatch(sql.FieldIsNull(FieldSignatureVendor))
}

// SignatureVendorNotNil applies the NotNil predicate on the "signature_vendor" field.
func SignatureVendorNotNil() predicate.CodeSignatureMatch {
	return predicate.CodeSignatureMatch(sql.FieldNotNull(FieldSignatureVendor))
}

// SignatureVendorEqualFold applies the EqualFold predicate on the "signature_vendor" field.
func SignatureVendorEqualFold(v string) predicate.CodeSignatureMatch {
	return predicate.CodeSignatureMatch(sql.FieldEqualFold(FieldSignatureVendor, v))
}

// SignatureVendorContainsFold applies the ContainsFold predicate on the "signature_vendor" field.
func SignatureVendorContainsFold(v string) predicate.CodeSignatureMatch {
	return predicate.CodeSignatureMatch(sql.FieldContainsFold(FieldSignatureVendor, v))
}

// SignatureProductEQ applies the EQ predicate on the "signature_product" field.
func SignatureProductEQ(v string) predicate.CodeSignatureMatch {
	return predicate.CodeSignatureMatch(sql.FieldEQ(FieldSignatureProduct, v))
}

// SignatureProductNEQ applies the NEQ predicate on the "signature_product" field.
func SignatureProductNEQ(v string) predicate.CodeSignatureMatch {
	return predicate.CodeSignatureMatch(sql.FieldNEQ(FieldSignatureProduct, v))
}

// SignatureProductIn applies the In predicate on the "signature_product" field.
func SignatureProductIn(vs ...string) predicate.CodeSignatureMatch {
	return predicate.CodeSignatureMatch(sql.FieldIn(FieldSignatureProduct, vs...))
}

// SignatureProductNotIn applies the NotIn predicate on the "signature_product" field.
func SignatureProductNotIn(vs ...string) predicate.CodeSignatureMatch {
	return predicate.CodeSignatureMatch(sql.FieldNotIn(FieldSignatureProduct, vs...))
}

// SignatureProductGT applies the GT predicate on the "signature_product" field.
func SignatureProductGT(v string) predicate.CodeSignatureMatch {
	return predicate.CodeSignatureMatch(sql.FieldGT(FieldSignatureProduct, v))
}

// SignatureProductGTE applies the GTE predicate on the "signature_product" field.
func SignatureProductGTE(v string) predicate.CodeSignatureMatch {
	return predicate.CodeSignatureMatch(sql.FieldGTE(FieldSignatureProduct, v))
}

// SignatureProductLT applies the LT predicate on the "signature_product" field.
func SignatureProductLT(v string) predicate.CodeSignatureMatch {
	return predicate.CodeSignatureMatch(sql.FieldLT(FieldSignatureProduct, v))
}

// SignatureProductLTE applies the LTE predicate on the "signature_product" field.
func SignatureProductLTE(v string) predicate.CodeSignatureMatch {
	return predicate.CodeSignatureMatch(sql.FieldLTE(FieldSignatureProduct, v))
}

// SignatureProductContains applies the Contains predicate on the "signature_product" field.
func SignatureProductContains(v string) predicate.CodeSignatureMatch {
	return predicate.CodeSignatureMatch(sql.FieldContains(FieldSignatureProduct, v))
}

// SignatureProductHasPrefix applies the HasPrefix predicate on the "signature_product" field.
func SignatureProductHasPrefix(v string) predicate.CodeSignatureMatch {
	return predicate.CodeSignatureMatch(sql.FieldHasPrefix(FieldSignatureProduct, v))
}

// SignatureProductHasSuffix applies the HasSuffix predicate on the "signature_product" field.
func SignatureProductHasSuffix(v string) predicate.CodeSignatureMatch {
	return predicate.CodeSignatureMatch(sql.FieldHasSuffix(FieldSignatureProduct, v))
}

// SignatureProductIsNil applies the IsNil predicate on the "signature_product" field.
func SignatureProductIsNil() predicate.CodeSignatureMatch {
	return predicate.CodeSignatureMatch(sql.FieldIsNull(FieldSignatureProduct))
}

// SignatureProductNotNil applies the NotNil predicate on the "signature_product" field.
func SignatureProductNotNil() predicate.CodeSignatureMatch {
	return predicate.CodeSignatureMatch(sql.FieldNotNull(FieldSignatureProduct))
}

// SignatureProductEqualFold applies the EqualFold predicate on the "signature_product" field.
func SignatureProductEqualFold(v string) predicate.CodeSignatureMatch {
	return predicate.CodeSignatureMatch(sql.FieldEqualFold(FieldSignatureProduct, v))
}

// SignatureProductContainsFold applies the ContainsFold predicate on the "signature_product" field.
func SignatureProductContainsFold(v string) predicate.CodeSignatureMatch {
	return predicate.CodeSignatureMatch(sql.FieldContainsFold(FieldSignatureProduct, v))
}

// SignatureServiceEQ applies the EQ predicate on the "signature_service" field.
func SignatureServiceEQ(v string) predicate.CodeSignatureMatch {
	return predicate.CodeSignatureMatch(sql.FieldEQ(FieldSignatureService, v))
}

// SignatureServiceNEQ applies the NEQ predicate on the "signature_service" field.
func SignatureServiceNEQ(v string) predicate.CodeSignatureMatch {
	return predicate.CodeSignatureMatch(sql.FieldNEQ(FieldSignatureService, v))
}

// SignatureServiceIn applies the In predicate on the "signature_service" field.
func SignatureServiceIn(vs ...string) predicate.CodeSignatureMatch {
	return predicate.CodeSignatureMatch(sql.FieldIn(FieldSignatureService, vs...))
}

// SignatureServiceNotIn applies the NotIn predicate on the "signature_service" field.
func SignatureServiceNotIn(vs ...string) predicate.CodeSignatureMatch {
	return predicate.CodeSignatureMatch(sql.FieldNotIn(FieldSignatureService, vs...))
}

// SignatureServiceGT applies the GT predicate on the "signature_service" field.
func SignatureServiceGT(v string) predicate.CodeSignatureMatch {
	return predicate.CodeSignatureMatch(sql.FieldGT(FieldSignatureService, v))
}

// SignatureServiceGTE applies the GTE predicate on the "signature_service" field.
func SignatureServiceGTE(v string) predicate.CodeSignatureMatch {
	return predicate.CodeSignatureMatch(sql.FieldGTE(FieldSignatureService, v))
}

// SignatureServiceLT applies the LT predicate on the "signature_service" field.
func SignatureServiceLT(v string) predicate.CodeSignatureMatch {
	return predicate.CodeSignatureMatch(sql.FieldLT(FieldSignatureService, v))
}

// SignatureServiceLTE applies the LTE predicate on the "signature_service" field.
func SignatureServiceLTE(v string) predicate.CodeSignatureMatch {
	return predicate.CodeSignatureMatch(sql.FieldLTE(FieldSignatureService, v))
}

// SignatureServiceContains applies the Contains predicate on the "signature_service" field.
func SignatureServiceContains(v string) predicate.CodeSignatureMatch {
	return predicate.CodeSignatureMatch(sql.FieldContains(FieldSignatureService, v))
}

// SignatureServiceHasPrefix applies the HasPrefix predicate on the "signature_service" field.
func SignatureServiceHasPrefix(v string) predicate.CodeSignatureMatch {
	return predicate.CodeSignatureMatch(sql.FieldHasPrefix(FieldSignatureService, v))
}

// SignatureServiceHasSuffix applies the HasSuffix predicate on the "signature_service" field.
func SignatureServiceHasSuffix(v string) predicate.CodeSignatureMatch {
	return predicate.CodeSignatureMatch(sql.FieldHasSuffix(FieldSignatureService, v))
}

// SignatureServiceIsNil applies the IsNil predicate on the "signature_service" field.
func SignatureServiceIsNil() predicate.CodeSignatureMatch {
	return predicate.CodeSignatureMatch(sql.FieldIsNull(FieldSignatureService))
}

// SignatureServiceNotNil applies the NotNil predicate on the "signature_service" field.
func SignatureServiceNotNil() predicate.CodeSignatureMatch {
	return predicate.CodeSignatureMatch(sql.FieldNotNull(FieldSignatureService))
}

// SignatureServiceEqualFold applies the EqualFold predicate on the "signature_service" field.
func SignatureServiceEqualFold(v string) predicate.CodeSignatureMatch {
	return predicate.CodeSignatureMatch(sql.FieldEqualFold(FieldSignatureService, v))
}

// SignatureServiceContainsFold applies the ContainsFold predicate on the "signature_service" field.
func SignatureServiceContainsFold(v string) predicate.CodeSignatureMatch {
	return predicate.CodeSignatureMatch(sql.FieldContainsFold(FieldSignatureService, v))
}

// SignatureDescriptionEQ applies the EQ predicate on the "signature_description" field.
func SignatureDescriptionEQ(v string) predicate.CodeSignatureMatch {
	return predicate.CodeSignatureMatch(sql.FieldEQ(FieldSignatureDescription, v))
}

// SignatureDescriptionNEQ applies the NEQ predicate on the "signature_description" field.
func SignatureDescriptionNEQ(v string) predicate.CodeSignatureMatch {
	return predicate.CodeSignatureMatch(sql.FieldNEQ(FieldSignatureDescription, v))
}

// SignatureDescriptionIn applies the In predicate on the "signature_description" field.
func SignatureDescriptionIn(vs ...string) predicate.CodeSignatureMatch {
	return predicate.CodeSignatureMatch(sql.FieldIn(FieldSignatureDescription, vs...))
}

// SignatureDescriptionNotIn applies the NotIn predicate on the "signature_description" field.
func SignatureDescriptionNotIn(vs ...string) predicate.CodeSignatureMatch {
	return predicate.CodeSignatureMatch(sql.FieldNotIn(FieldSignatureDescription, vs...))
}

// SignatureDescriptionGT applies the GT predicate on the "signature_description" field.
func SignatureDescriptionGT(v string) predicate.CodeSignatureMatch {
	return predicate.CodeSignatureMatch(sql.FieldGT(FieldSignatureDescription, v))
}

// SignatureDescriptionGTE applies the GTE predicate on the "signature_description" field.
func SignatureDescriptionGTE(v string) predicate.CodeSignatureMatch {
	return predicate.CodeSignatureMatch(sql.FieldGTE(FieldSignatureDescription, v))
}

// SignatureDescriptionLT applies the LT predicate on the "signature_description" field.
func SignatureDescriptionLT(v string) predicate.CodeSignatureMatch {
	return predicate.CodeSignatureMatch(sql.FieldLT(FieldSignatureDescription, v))
}

// SignatureDescriptionLTE applies the LTE predicate on the "signature_description" field.
func SignatureDescriptionLTE(v string) predicate.CodeSignatureMatch {
	return predicate.CodeSignatureMatch(sql.FieldLTE(FieldSignatureDescription, v))
}

// SignatureDescriptionContains applies the Contains predicate on the "signature_description" field.
func SignatureDescriptionContains(v string) predicate.CodeSignatureMatch {
	return predicate.CodeSignatureMatch(sql.FieldContains(FieldSignatureDescription, v))
}

// SignatureDescriptionHasPrefix applies the HasPrefix predicate on the "signature_description" field.
func SignatureDescriptionHasPrefix(v string) predicate.CodeSignatureMatch {
	return predicate.CodeSignatureMatch(sql.FieldHasPrefix(FieldSignatureDescription, v))
}

// SignatureDescriptionHasSuffix applies the HasSuffix predicate on the "signature_description" field.
func SignatureDescriptionHasSuffix(v string) predicate.CodeSignatureMatch {
	return predicate.CodeSignatureMatch(sql.FieldHasSuffix(FieldSignatureDescription, v))
}

// SignatureDescriptionIsNil applies the IsNil predicate on the "signature_description" field.
func SignatureDescriptionIsNil() predicate.CodeSignatureMatch {
	return predicate.CodeSignatureMatch(sql.FieldIsNull(FieldSignatureDescription))
}

// SignatureDescriptionNotNil applies the NotNil predicate on the "signature_description" field.
func SignatureDescriptionNotNil() predicate.CodeSignatureMatch {
	return predicate.CodeSignatureMatch(sql.FieldNotNull(FieldSignatureDescription))
}

// SignatureDescriptionEqualFold applies the EqualFold predicate on the "signature_description" field.
func SignatureDescriptionEqualFold(v string) predicate.CodeSignatureMatch {
	return predicate.CodeSignatureMatch(sql.FieldEqualFold(FieldSignatureDescription, v))
}

// SignatureDescriptionContainsFold applies the ContainsFold predicate on the "signature_description" field.
func SignatureDescriptionContainsFold(v string) predicate.CodeSignatureMatch {
	return predicate.CodeSignatureMatch(sql.FieldContainsFold(FieldSignatureDescription, v))
}

// TagsIsNil applies the IsNil predicate on the "tags" field.
func TagsIsNil() predicate.CodeSignatureMatch {
	return predicate.CodeSignatureMatch(sql.FieldIsNull(FieldTags))
}

// TagsNotNil applies the NotNil predicate on the "tags" field.
func TagsNotNil() predicate.CodeSignatureMatch {
	return predicate.CodeSignatureMatch(sql.FieldNotNull(FieldTags))
}

// FilePathEQ applies the EQ predicate on the "file_path" field.
func FilePathEQ(v string) predicate.CodeSignatureMatch {
	return predicate.CodeSignatureMatch(sql.FieldEQ(FieldFilePath, v))
}

// FilePathNEQ applies the NEQ predicate on the "file_path" field.
func FilePathNEQ(v string) predicate.CodeSignatureMatch {
	return predicate.CodeSignatureMatch(sql.FieldNEQ(FieldFilePath, v))
}

// FilePathIn applies the In predicate on the "file_path" field.
func FilePathIn(vs ...string) predicate.CodeSignatureMatch {
	return predicate.CodeSignatureMatch(sql.FieldIn(FieldFilePath, vs...))
}

// FilePathNotIn applies the NotIn predicate on the "file_path" field.
func FilePathNotIn(vs ...string) predicate.CodeSignatureMatch {
	return predicate.CodeSignatureMatch(sql.FieldNotIn(FieldFilePath, vs...))
}

// FilePathGT applies the GT predicate on the "file_path" field.
func FilePathGT(v string) predicate.CodeSignatureMatch {
	return predicate.CodeSignatureMatch(sql.FieldGT(FieldFilePath, v))
}

// FilePathGTE applies the GTE predicate on the "file_path" field.
func FilePathGTE(v string) predicate.CodeSignatureMatch {
	return predicate.CodeSignatureMatch(sql.FieldGTE(FieldFilePath, v))
}

// FilePathLT applies the LT predicate on the "file_path" field.
func FilePathLT(v string) predicate.CodeSignatureMatch {
	return predicate.CodeSignatureMatch(sql.FieldLT(FieldFilePath, v))
}

// FilePathLTE applies the LTE predicate on the "file_path" field.
func FilePathLTE(v string) predicate.CodeSignatureMatch {
	return predicate.CodeSignatureMatch(sql.FieldLTE(FieldFilePath, v))
}

// FilePathContains applies the Contains predicate on the "file_path" field.
func FilePathContains(v string) predicate.CodeSignatureMatch {
	return predicate.CodeSignatureMatch(sql.FieldContains(FieldFilePath, v))
}

// FilePathHasPrefix applies the HasPrefix predicate on the "file_path" field.
func FilePathHasPrefix(v string) predicate.CodeSignatureMatch {
	return predicate.CodeSignatureMatch(sql.FieldHasPrefix(FieldFilePath, v))
}

// FilePathHasSuffix applies the HasSuffix predicate on the "file_path" field.
func FilePathHasSuffix(v string) predicate.CodeSignatureMatch {
	return predicate.CodeSignatureMatch(sql.FieldHasSuffix(FieldFilePath, v))
}

// FilePathEqualFold applies the EqualFold predicate on the "file_path" field.
func FilePathEqualFold(v string) predicate.CodeSignatureMatch {
	return predicate.CodeSignatureMatch(sql.FieldEqualFold(FieldFilePath, v))
}

// FilePathContainsFold applies the ContainsFold predicate on the "file_path" field.
func FilePathContainsFold(v string) predicate.CodeSignatureMatch {
	return predicate.CodeSignatureMatch(sql.FieldContainsFold(FieldFilePath, v))
}

// LanguageEQ applies the EQ predicate on the "language" field.
func LanguageEQ(v string) predicate.CodeSignatureMatch {
	return predicate.CodeSignatureMatch(sql.FieldEQ(FieldLanguage, v))
}

// LanguageNEQ applies the NEQ predicate on the "language" field.
func LanguageNEQ(v string) predicate.CodeSignatureMatch {
	return predicate.CodeSignatureMatch(sql.FieldNEQ(FieldLanguage, v))
}

// LanguageIn applies the In predicate on the "language" field.
func LanguageIn(vs ...string) predicate.CodeSignatureMatch {
	return predicate.CodeSignatureMatch(sql.FieldIn(FieldLanguage, vs...))
}

// LanguageNotIn applies the NotIn predicate on the "language" field.
func LanguageNotIn(vs ...string) predicate.CodeSignatureMatch {
	return predicate.CodeSignatureMatch(sql.FieldNotIn(FieldLanguage, vs...))
}

// LanguageGT applies the GT predicate on the "language" field.
func LanguageGT(v string) predicate.CodeSignatureMatch {
	return predicate.CodeSignatureMatch(sql.FieldGT(FieldLanguage, v))
}

// LanguageGTE applies the GTE predicate on the "language" field.
func LanguageGTE(v string) predicate.CodeSignatureMatch {
	return predicate.CodeSignatureMatch(sql.FieldGTE(FieldLanguage, v))
}

// LanguageLT applies the LT predicate on the "language" field.
func LanguageLT(v string) predicate.CodeSignatureMatch {
	return predicate.CodeSignatureMatch(sql.FieldLT(FieldLanguage, v))
}

// LanguageLTE applies the LTE predicate on the "language" field.
func LanguageLTE(v string) predicate.CodeSignatureMatch {
	return predicate.CodeSignatureMatch(sql.FieldLTE(FieldLanguage, v))
}

// LanguageContains applies the Contains predicate on the "language" field.
func LanguageContains(v string) predicate.CodeSignatureMatch {
	return predicate.CodeSignatureMatch(sql.FieldContains(FieldLanguage, v))
}

// LanguageHasPrefix applies the HasPrefix predicate on the "language" field.
func LanguageHasPrefix(v string) predicate.CodeSignatureMatch {
	return predicate.CodeSignatureMatch(sql.FieldHasPrefix(FieldLanguage, v))
}

// LanguageHasSuffix applies the HasSuffix predicate on the "language" field.
func LanguageHasSuffix(v string) predicate.CodeSignatureMatch {
	return predicate.CodeSignatureMatch(sql.FieldHasSuffix(FieldLanguage, v))
}

// LanguageEqualFold applies the EqualFold predicate on the "language" field.
func LanguageEqualFold(v string) predicate.CodeSignatureMatch {
	return predicate.CodeSignatureMatch(sql.FieldEqualFold(FieldLanguage, v))
}

// LanguageContainsFold applies the ContainsFold predicate on the "language" field.
func LanguageContainsFold(v string) predicate.CodeSignatureMatch {
	return predicate.CodeSignatureMatch(sql.FieldContainsFold(FieldLanguage, v))
}

// LineEQ applies the EQ predicate on the "line" field.
func LineEQ(v uint) predicate.CodeSignatureMatch {
	return predicate.CodeSignatureMatch(sql.FieldEQ(FieldLine, v))
}

// LineNEQ applies the NEQ predicate on the "line" field.
func LineNEQ(v uint) predicate.CodeSignatureMatch {
	return predicate.CodeSignatureMatch(sql.FieldNEQ(FieldLine, v))
}

// LineIn applies the In predicate on the "line" field.
func LineIn(vs ...uint) predicate.CodeSignatureMatch {
	return predicate.CodeSignatureMatch(sql.FieldIn(FieldLine, vs...))
}

// LineNotIn applies the NotIn predicate on the "line" field.
func LineNotIn(vs ...uint) predicate.CodeSignatureMatch {
	return predicate.CodeSignatureMatch(sql.FieldNotIn(FieldLine, vs...))
}

// LineGT applies the GT predicate on the "line" field.
func LineGT(v uint) predicate.CodeSignatureMatch {
	return predicate.CodeSignatureMatch(sql.FieldGT(FieldLine, v))
}

// LineGTE applies the GTE predicate on the "line" field.
func LineGTE(v uint) predicate.CodeSignatureMatch {
	return predicate.CodeSignatureMatch(sql.FieldGTE(FieldLine, v))
}

// LineLT applies the LT predicate on the "line" field.
func LineLT(v uint) predicate.CodeSignatureMatch {
	return predicate.CodeSignatureMatch(sql.FieldLT(FieldLine, v))
}

// LineLTE applies the LTE predicate on the "line" field.
func LineLTE(v uint) predicate.CodeSignatureMatch {
	return predicate.CodeSignatureMatch(sql.FieldLTE(FieldLine, v))
}

// LineIsNil applies the IsNil predicate on the "line" field.
func LineIsNil() predicate.CodeSignatureMatch {
	return predicate.CodeSignatureMatch(sql.FieldIsNull(FieldLine))
}

// LineNotNil applies the NotNil predicate on the "line" field.
func LineNotNil() predicate.CodeSignatureMatch {
	return predicate.CodeSignatureMatch(sql.FieldNotNull(FieldLine))
}

// ColumnEQ applies the EQ predicate on the "column" field.
func ColumnEQ(v uint) predicate.CodeSignatureMatch {
	return predicate.CodeSignatureMatch(sql.FieldEQ(FieldColumn, v))
}

// ColumnNEQ applies the NEQ predicate on the "column" field.
func ColumnNEQ(v uint) predicate.CodeSignatureMatch {
	return predicate.CodeSignatureMatch(sql.FieldNEQ(FieldColumn, v))
}

// ColumnIn applies the In predicate on the "column" field.
func ColumnIn(vs ...uint) predicate.CodeSignatureMatch {
	return predicate.CodeSignatureMatch(sql.FieldIn(FieldColumn, vs...))
}

// ColumnNotIn applies the NotIn predicate on the "column" field.
func ColumnNotIn(vs ...uint) predicate.CodeSignatureMatch {
	return predicate.CodeSignatureMatch(sql.FieldNotIn(FieldColumn, vs...))
}

// ColumnGT applies the GT predicate on the "column" field.
func ColumnGT(v uint) predicate.CodeSignatureMatch {
	return predicate.CodeSignatureMatch(sql.FieldGT(FieldColumn, v))
}

// ColumnGTE applies the GTE predicate on the "column" field.
func ColumnGTE(v uint) predicate.CodeSignatureMatch {
	return predicate.CodeSignatureMatch(sql.FieldGTE(FieldColumn, v))
}

// ColumnLT applies the LT predicate on the "column" field.
func ColumnLT(v uint) predicate.CodeSignatureMatch {
	return predicate.CodeSignatureMatch(sql.FieldLT(FieldColumn, v))
}

// ColumnLTE applies the LTE predicate on the "column" field.
func ColumnLTE(v uint) predicate.CodeSignatureMatch {
	return predicate.CodeSignatureMatch(sql.FieldLTE(FieldColumn, v))
}

// ColumnIsNil applies the IsNil predicate on the "column" field.
func ColumnIsNil() predicate.CodeSignatureMatch {
	return predicate.CodeSignatureMatch(sql.FieldIsNull(FieldColumn))
}

// ColumnNotNil applies the NotNil predicate on the "column" field.
func ColumnNotNil() predicate.CodeSignatureMatch {
	return predicate.CodeSignatureMatch(sql.FieldNotNull(FieldColumn))
}

// CalleeNamespaceEQ applies the EQ predicate on the "callee_namespace" field.
func CalleeNamespaceEQ(v string) predicate.CodeSignatureMatch {
	return predicate.CodeSignatureMatch(sql.FieldEQ(FieldCalleeNamespace, v))
}

// CalleeNamespaceNEQ applies the NEQ predicate on the "callee_namespace" field.
func CalleeNamespaceNEQ(v string) predicate.CodeSignatureMatch {
	return predicate.CodeSignatureMatch(sql.FieldNEQ(FieldCalleeNamespace, v))
}

// CalleeNamespaceIn applies the In predicate on the "callee_namespace" field.
func CalleeNamespaceIn(vs ...string) predicate.CodeSignatureMatch {
	return predicate.CodeSignatureMatch(sql.FieldIn(FieldCalleeNamespace, vs...))
}

// CalleeNamespaceNotIn applies the NotIn predicate on the "callee_namespace" field.
func CalleeNamespaceNotIn(vs ...string) predicate.CodeSignatureMatch {
	return predicate.CodeSignatureMatch(sql.FieldNotIn(FieldCalleeNamespace, vs...))
}

// CalleeNamespaceGT applies the GT predicate on the "callee_namespace" field.
func CalleeNamespaceGT(v string) predicate.CodeSignatureMatch {
	return predicate.CodeSignatureMatch(sql.FieldGT(FieldCalleeNamespace, v))
}

// CalleeNamespaceGTE applies the GTE predicate on the "callee_namespace" field.
func CalleeNamespaceGTE(v string) predicate.CodeSignatureMatch {
	return predicate.CodeSignatureMatch(sql.FieldGTE(FieldCalleeNamespace, v))
}

// CalleeNamespaceLT applies the LT predicate on the "callee_namespace" field.
func CalleeNamespaceLT(v string) predicate.CodeSignatureMatch {
	return predicate.CodeSignatureMatch(sql.FieldLT(FieldCalleeNamespace, v))
}

// CalleeNamespaceLTE applies the LTE predicate on the "callee_namespace" field.
func CalleeNamespaceLTE(v string) predicate.CodeSignatureMatch {
	return predicate.CodeSignatureMatch(sql.FieldLTE(FieldCalleeNamespace, v))
}

// CalleeNamespaceContains applies the Contains predicate on the "callee_namespace" field.
func CalleeNamespaceContains(v string) predicate.CodeSignatureMatch {
	return predicate.CodeSignatureMatch(sql.FieldContains(FieldCalleeNamespace, v))
}

// CalleeNamespaceHasPrefix applies the HasPrefix predicate on the "callee_namespace" field.
func CalleeNamespaceHasPrefix(v string) predicate.CodeSignatureMatch {
	return predicate.CodeSignatureMatch(sql.FieldHasPrefix(FieldCalleeNamespace, v))
}

// CalleeNamespaceHasSuffix applies the HasSuffix predicate on the "callee_namespace" field.
func CalleeNamespaceHasSuffix(v string) predicate.CodeSignatureMatch {
	return predicate.CodeSignatureMatch(sql.FieldHasSuffix(FieldCalleeNamespace, v))
}

// CalleeNamespaceIsNil applies the IsNil predicate on the "callee_namespace" field.
func CalleeNamespaceIsNil() predicate.CodeSignatureMatch {
	return predicate.CodeSignatureMatch(sql.FieldIsNull(FieldCalleeNamespace))
}

// CalleeNamespaceNotNil applies the NotNil predicate on the "callee_namespace" field.
func CalleeNamespaceNotNil() predicate.CodeSignatureMatch {
	return predicate.CodeSignatureMatch(sql.FieldNotNull(FieldCalleeNamespace))
}

// CalleeNamespaceEqualFold applies the EqualFold predicate on the "callee_namespace" field.
func CalleeNamespaceEqualFold(v string) predicate.CodeSignatureMatch {
	return predicate.CodeSignatureMatch(sql.FieldEqualFold(FieldCalleeNamespace, v))
}

// CalleeNamespaceContainsFold applies the ContainsFold predicate on the "callee_namespace" field.
func CalleeNamespaceContainsFold(v string) predicate.CodeSignatureMatch {
	return predicate.CodeSignatureMatch(sql.FieldContainsFold(FieldCalleeNamespace, v))
}

// MatchedCallEQ applies the EQ predicate on the "matched_call" field.
func MatchedCallEQ(v string) predicate.CodeSignatureMatch {
	return predicate.CodeSignatureMatch(sql.FieldEQ(FieldMatchedCall, v))
}

// MatchedCallNEQ applies the NEQ predicate on the "matched_call" field.
func MatchedCallNEQ(v string) predicate.CodeSignatureMatch {
	return predicate.CodeSignatureMatch(sql.FieldNEQ(FieldMatchedCall, v))
}

// MatchedCallIn applies the In predicate on the "matched_call" field.
func MatchedCallIn(vs ...string) predicate.CodeSignatureMatch {
	return predicate.CodeSignatureMatch(sql.FieldIn(FieldMatchedCall, vs...))
}

// MatchedCallNotIn applies the NotIn predicate on the "matched_call" field.
func MatchedCallNotIn(vs ...string) predicate.CodeSignatureMatch {
	return predicate.CodeSignatureMatch(sql.FieldNotIn(FieldMatchedCall, vs...))
}

// MatchedCallGT applies the GT predicate on the "matched_call" field.
func MatchedCallGT(v string) predicate.CodeSignatureMatch {
	return predicate.CodeSignatureMatch(sql.FieldGT(FieldMatchedCall, v))
}

// MatchedCallGTE applies the GTE predicate on the "matched_call" field.
func MatchedCallGTE(v string) predicate.CodeSignatureMatch {
	return predicate.CodeSignatureMatch(sql.FieldGTE(FieldMatchedCall, v))
}

// MatchedCallLT applies the LT predicate on the "matched_call" field.
func MatchedCallLT(v string) predicate.CodeSignatureMatch {
	return predicate.CodeSignatureMatch(sql.FieldLT(FieldMatchedCall, v))
}

// MatchedCallLTE applies the LTE predicate on the "matched_call" field.
func MatchedCallLTE(v string) predicate.CodeSignatureMatch {
	return predicate.CodeSignatureMatch(sql.FieldLTE(FieldMatchedCall, v))
}

// MatchedCallContains applies the Contains predicate on the "matched_call" field.
func MatchedCallContains(v string) predicate.CodeSignatureMatch {
	return predicate.CodeSignatureMatch(sql.FieldContains(FieldMatchedCall, v))
}

// MatchedCallHasPrefix applies the HasPrefix predicate on the "matched_call" field.
func MatchedCallHasPrefix(v string) predicate.CodeSignatureMatch {
	return predicate.CodeSignatureMatch(sql.FieldHasPrefix(FieldMatchedCall, v))
}

// MatchedCallHasSuffix applies the HasSuffix predicate on the "matched_call" field.
func MatchedCallHasSuffix(v string) predicate.CodeSignatureMatch {
	return predicate.CodeSignatureMatch(sql.FieldHasSuffix(FieldMatchedCall, v))
}

// MatchedCallIsNil applies the IsNil predicate on the "matched_call" field.
func MatchedCallIsNil() predicate.CodeSignatureMatch {
	return predicate.CodeSignatureMatch(sql.FieldIsNull(FieldMatchedCall))
}

// MatchedCallNotNil applies the NotNil predicate on the "matched_call" field.
func MatchedCallNotNil() predicate.CodeSignatureMatch {
	return predicate.CodeSignatureMatch(sql.FieldNotNull(FieldMatchedCall))
}

// MatchedCallEqualFold applies the EqualFold predicate on the "matched_call" field.
func MatchedCallEqualFold(v string) predicate.CodeSignatureMatch {
	return predicate.CodeSignatureMatch(sql.FieldEqualFold(FieldMatchedCall, v))
}

// MatchedCallContainsFold applies the ContainsFold predicate on the "matched_call" field.
func MatchedCallContainsFold(v string) predicate.CodeSignatureMatch {
	return predicate.CodeSignatureMatch(sql.FieldContainsFold(FieldMatchedCall, v))
}

// PackageHintEQ applies the EQ predicate on the "package_hint" field.
func PackageHintEQ(v string) predicate.CodeSignatureMatch {
	return predicate.CodeSignatureMatch(sql.FieldEQ(FieldPackageHint, v))
}

// PackageHintNEQ applies the NEQ predicate on the "package_hint" field.
func PackageHintNEQ(v string) predicate.CodeSignatureMatch {
	return predicate.CodeSignatureMatch(sql.FieldNEQ(FieldPackageHint, v))
}

// PackageHintIn applies the In predicate on the "package_hint" field.
func PackageHintIn(vs ...string) predicate.CodeSignatureMatch {
	return predicate.CodeSignatureMatch(sql.FieldIn(FieldPackageHint, vs...))
}

// PackageHintNotIn applies the NotIn predicate on the "package_hint" field.
func PackageHintNotIn(vs ...string) predicate.CodeSignatureMatch {
	return predicate.CodeSignatureMatch(sql.FieldNotIn(FieldPackageHint, vs...))
}

// PackageHintGT applies the GT predicate on the "package_hint" field.
func PackageHintGT(v string) predicate.CodeSignatureMatch {
	return predicate.CodeSignatureMatch(sql.FieldGT(FieldPackageHint, v))
}

// PackageHintGTE applies the GTE predicate on the "package_hint" field.
func PackageHintGTE(v string) predicate.CodeSignatureMatch {
	return predicate.CodeSignatureMatch(sql.FieldGTE(FieldPackageHint, v))
}

// PackageHintLT applies the LT predicate on the "package_hint" field.
func PackageHintLT(v string) predicate.CodeSignatureMatch {
	return predicate.CodeSignatureMatch(sql.FieldLT(FieldPackageHint, v))
}

// PackageHintLTE applies the LTE predicate on the "package_hint" field.
func PackageHintLTE(v string) predicate.CodeSignatureMatch {
	return predicate.CodeSignatureMatch(sql.FieldLTE(FieldPackageHint, v))
}

// PackageHintContains applies the Contains predicate on the "package_hint" field.
func PackageHintContains(v string) predicate.CodeSignatureMatch {
	return predicate.CodeSignatureMatch(sql.FieldContains(FieldPackageHint, v))
}

// PackageHintHasPrefix applies the HasPrefix predicate on the "package_hint" field.
func PackageHintHasPrefix(v string) predicate.CodeSignatureMatch {
	return predicate.CodeSignatureMatch(sql.FieldHasPrefix(FieldPackageHint, v))
}

// PackageHintHasSuffix applies the HasSuffix predicate on the "package_hint" field.
func PackageHintHasSuffix(v string) predicate.CodeSignatureMatch {
	return predicate.CodeSignatureMatch(sql.FieldHasSuffix(FieldPackageHint, v))
}

// PackageHintIsNil applies the IsNil predicate on the "package_hint" field.
func PackageHintIsNil() predicate.CodeSignatureMatch {
	return predicate.CodeSignatureMatch(sql.FieldIsNull(FieldPackageHint))
}

// PackageHintNotNil applies the NotNil predicate on the "package_hint" field.
func PackageHintNotNil() predicate.CodeSignatureMatch {
	return predicate.CodeSignatureMatch(sql.FieldNotNull(FieldPackageHint))
}

// PackageHintEqualFold applies the EqualFold predicate on the "package_hint" field.
func PackageHintEqualFold(v string) predicate.CodeSignatureMatch {
	return predicate.CodeSignatureMatch(sql.FieldEqualFold(FieldPackageHint, v))
}

// PackageHintContainsFold applies the ContainsFold predicate on the "package_hint" field.
func PackageHintContainsFold(v string) predicate.CodeSignatureMatch {
	return predicate.CodeSignatureMatch(sql.FieldContainsFold(FieldPackageHint, v))
}

// HasSourceFile applies the HasEdge predicate on the "source_file" edge.
func HasSourceFile() predicate.CodeSignatureMatch {
	return predicate.CodeSignatureMatch(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, false, SourceFileTable, SourceFileColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasSourceFileWith applies the HasEdge predicate on the "source_file" edge with a given conditions (other predicates).
func HasSourceFileWith(preds ...predicate.CodeSourceFile) predicate.CodeSignatureMatch {
	return predicate.CodeSignatureMatch(func(s *sql.Selector) {
		step := newSourceFileStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.CodeSignatureMatch) predicate.CodeSignatureMatch {
	return predicate.CodeSignatureMatch(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.CodeSignatureMatch) predicate.CodeSignatureMatch {
	return predicate.CodeSignatureMatch(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.CodeSignatureMatch) predicate.CodeSignatureMatch {
	return predicate.CodeSignatureMatch(sql.NotPredicates(p))
}
