name: Deploy to Github Pages
on:
  push:
    branches:
      - manual

jobs:
  deploy:
    name: Deploy to Github Pages
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - name: Set up Go
        uses: actions/setup-go@0aaccfd150d50ccaeb58ebd88d36e91967a5f35b # v5
        with:
          go-version-file: go.mod

      - name: Build vet
        run: 
          go build

      - name: Generate MD Docs in public folder
        run: 
          ./vet doc generate --markdown public

      - name: remove .nojekyll file
        run: 
          rm ./public/.nojekyll

      - name: Deploy to Github Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
