name: Secrets Scan
on:
  pull_request:
    branches:
      - main

permissions:
  contents: read

jobs:
  trufflehog:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: Checkout Source
        uses: actions/checkout@ee0669bd1cc54295c223e0bb666b733df41de1c5
        with:
          fetch-depth: '0'
      - name: TruffleHog OSS
        uses: trufflesecurity/trufflehog@8b6f55b592e46ac44a42dc3e3dee0ebcc0f56df5
        with:
          path: ./
          base: ${{ github.event.pull_request.base.sha }}
          head: ${{ github.event.pull_request.head.sha }} 

