name: Container Scan E2E

on:
  push:
    branches: [ main ]
  pull_request:

permissions: read-all

jobs:
  e2e-scan:
    name: E2E Scan on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
      - name: Checkout Source
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5

      - name: Set up Go
        uses: actions/setup-go@44694675825211faa026b3c33043df3e48a5fa00 # v6
        with:
          go-version-file: go.mod

      - name: Build and Test
        run: |
          make

      - name: Run container scan tests
        shell: bash
        run: |
          ./vet scan --image alpine:latest
          ./vet scan --image ghcr.io/safedep/vet:latest
          ./vet scan --image node:20
